LESSONS.push({
    id: 38,
    part: 2,
    titleTh: 'Vocabulary in Context: เดาศัพท์จากบริบท',
    titleEn: 'Vocabulary in Context',
    icon: '🔤',
    sections: [
        {
            type: 'intro',
            title: 'บทนำ: Context Clues (เบาะแสจากบริบท)',
            contentTh: 'ข้อสอบ CU-TEP มักจะถามว่า "คำนี้มีความหมายใกล้เคียงกับอะไร" ซึ่งไม่จำเป็นต้องรู้ศัพท์ตัวนั้นมาก่อน ให้ใช้ Context Clues (เบาะแสจากคำรอบข้าง) ในการเดา',
            contentEn: 'The CU-TEP often asks you to determine the meaning of a word based on its context. Use surrounding words, sentence structure, and logical reasoning to infer meaning.',
            bullets: ['Definition Clue: ประโยคบอกความหมายให้เลย (e.g., "Linguistics, the study of language, is...")', 'Contrast Clue: ใช้คำตรงข้าม (e.g., Unlike his timid brother, he was bold.)', 'Example Clue: ยกตัวอย่าง (e.g., Citrus fruits such as oranges and lemons...)']
        },
        {
            type: 'quiz',
            title: 'Quiz: Vocabulary in Context (15 ข้อ)',
            questions: [
                { question: '"The politician\'s speech was so ambiguous that nobody understood his actual position." What does "ambiguous" mean?', questionTh: '"ambiguous" แปลว่าอะไร?', choices: ['Clear', 'Lengthy', 'Unclear; open to multiple interpretations', 'Persuasive'], answer: 2, explanationTh: 'เบาะแส: "nobody understood his actual position" → คนฟังไม่เข้าใจ = กำกวม', explanationEn: 'The clue "nobody understood" indicates the speech was unclear.' },
                { question: '"After the grueling 12-hour shift, the nurse was utterly exhausted." What does "grueling" mean?', questionTh: '"grueling" แปลว่าอะไร?', choices: ['Easy', 'Short', 'Extremely tiring and demanding', 'Exciting'], answer: 2, explanationTh: 'เบาะแส: ทำงาน 12 ชั่วโมง + "utterly exhausted" (เหนื่อยสุดๆ)', explanationEn: 'Working 12 hours and being "utterly exhausted" indicates the shift was extremely demanding.' },
                { question: '"The judge showed great impartiality by treating both sides equally." What does "impartiality" mean?', questionTh: '"impartiality" แปลว่าอะไร?', choices: ['Bias', 'Fairness and lack of bias', 'Anger', 'Intelligence'], answer: 1, explanationTh: 'เบาะแส: "treating both sides equally" = ปฏิบัติต่อทั้งสองฝ่ายอย่างเท่าเทียม = ความเป็นกลาง', explanationEn: 'The definition clue "treating both sides equally" defines impartiality as fairness.' },
                { question: '"Unlike her gregarious sister who loved parties, Maya was shy and preferred solitude." What does "gregarious" mean?', questionTh: '"gregarious" แปลว่าอะไร?', choices: ['Shy', 'Sociable and outgoing', 'Angry', 'Lazy'], answer: 1, explanationTh: 'Contrast Clue: "Unlike" + Maya shy = ตรงข้ามกัน → gregarious = ชอบเข้าสังคม', explanationEn: '"Unlike" signals a contrast with "shy", meaning gregarious = sociable.' },
                { question: '"The new law was implemented to mitigate the effects of air pollution." What does "mitigate" mean?', questionTh: '"mitigate" แปลว่าอะไร?', choices: ['Increase', 'Ignore', 'Reduce the severity of', 'Celebrate'], answer: 2, explanationTh: 'กฎหมายมักจะออกมาเพื่อแก้ปัญหา → mitigate = ลดความรุนแรง/บรรเทา', explanationEn: 'Laws are created to solve problems. "Mitigate" means to reduce severity.' },
                { question: '"The country experienced a period of unprecedented prosperity, with GDP growth never seen before." What does "unprecedented" mean?', questionTh: '"unprecedented" แปลว่าอะไร?', choices: ['Expected', 'Never having happened before', 'Declining', 'Predictable'], answer: 1, explanationTh: 'เบาะแส: "never seen before" = ไม่เคยเกิดขึ้นมาก่อน', explanationEn: '"Never seen before" directly defines "unprecedented".' },
                { question: '"The scientist\'s hypothesis was subsequently confirmed by multiple independent studies." What does "subsequently" mean?', questionTh: '"subsequently" แปลว่าอะไร?', choices: ['Previously', 'Simultaneously', 'Afterward; later', 'Immediately'], answer: 2, explanationTh: 'สมมติฐานมาก่อน → ถูกยืนยัน "ในภายหลัง" โดยงานวิจัยอื่น', explanationEn: 'The hypothesis came first, then was confirmed later. "Subsequently" = afterward.' },
                { question: '"His frugal lifestyle allowed him to save enough money to retire early." What does "frugal" mean?', questionTh: '"frugal" แปลว่าอะไร?', choices: ['Wasteful', 'Economical and thrifty', 'Luxurious', 'Careless'], answer: 1, explanationTh: 'เบาะแส: "save enough money to retire early" = ออมเงินได้เยอะ = ใช้จ่ายประหยัด', explanationEn: 'Saving money to retire early implies a thrifty lifestyle.' },
                { question: '"The remote village was virtually inaccessible during the monsoon season due to flooded roads." What does "inaccessible" mean?', questionTh: '"inaccessible" แปลว่าอะไร?', choices: ['Easy to reach', 'Impossible or very hard to reach', 'Popular', 'Crowded'], answer: 1, explanationTh: 'เบาะแส: "remote" + "flooded roads" = ถนนน้ำท่วม เข้าถึงไม่ได้', explanationEn: 'Flooded roads in a remote area means the village cannot be reached.' },
                { question: '"The CEO\'s resignation was abrupt; no one had any warning." What does "abrupt" mean?', questionTh: '"abrupt" แปลว่าอะไร?', choices: ['Gradual', 'Planned', 'Sudden and unexpected', 'Smooth'], answer: 2, explanationTh: '"no one had any warning" = ไม่มีใครรู้ล่วงหน้า = กะทันหัน', explanationEn: '"No warning" indicates the resignation was sudden and unexpected.' },
                { question: '"Nocturnal animals, such as owls and bats, are most active during the night." What does "nocturnal" mean?', questionTh: '"nocturnal" แปลว่าอะไร?', choices: ['Active during the day', 'Active at night', 'Living in water', 'Living underground'], answer: 1, explanationTh: 'Example Clue: owls, bats + "active during the night" = สัตว์หากินกลางคืน', explanationEn: 'The examples (owls, bats) and the phrase "active during the night" define nocturnal.' },
                { question: '"Her candid response surprised everyone; most politicians would have been more diplomatic." What does "candid" mean?', questionTh: '"candid" แปลว่าอะไร?', choices: ['Deceptive', 'Honest and straightforward', 'Diplomatic', 'Quiet'], answer: 1, explanationTh: 'Contrast: "most politicians would have been more diplomatic" = คนอื่นจะพูดอ้อม แต่เธอตรงไปตรงมา', explanationEn: 'The contrast with "diplomatic" implies candid means direct and honest.' },
                { question: '"The company aims to foster innovation by encouraging creative thinking." What does "foster" mean?', questionTh: '"foster" แปลว่าอะไร?', choices: ['Prevent', 'Encourage and promote', 'Ignore', 'Copy'], answer: 1, explanationTh: 'เบาะแส: "by encouraging creative thinking" = ส่งเสริม/สนับสนุน', explanationEn: '"Encouraging creative thinking" clarifies that foster means to promote.' },
                { question: '"The dilapidated building posed a serious safety hazard to the public." What does "dilapidated" mean?', questionTh: '"dilapidated" แปลว่าอะไร?', choices: ['Newly constructed', 'In a state of disrepair', 'Beautifully decorated', 'Very tall'], answer: 1, explanationTh: 'เบาะแส: "safety hazard" = เป็นอันตราย → ตัวอาคารต้องเก่าทรุดโทรม', explanationEn: 'A "safety hazard" implies the building is in poor, deteriorated condition.' },
                { question: '"The negotiations reached an impasse, with neither side willing to compromise." What does "impasse" mean?', questionTh: '"impasse" แปลว่าอะไร?', choices: ['Agreement', 'A deadlock; a situation with no progress', 'Success', 'A celebration'], answer: 1, explanationTh: '"neither side willing to compromise" = ไม่มีฝ่ายไหนยอม = ทางตัน', explanationEn: '"Neither side willing to compromise" indicates a deadlock situation.' }
            ]
        }
    ]
});
