LESSONS.push({
    id: 98,
    part: 1,
    isGame: true,
    titleTh: 'เกมส์จับคู่คำศัพท์ ชุดที่ 2',
    titleEn: 'Vocab Listening Match Game — Set 2',
    icon: '🎮',
    sections: [
        {
            type: 'intro',
            title: 'กติกาการเล่น (How to play)',
            contentTh: 'ชุดที่ 2 รวมคำศัพท์ระดับกลาง-สูงกว่า 200 คำ! ฟังเสียงแล้วเลือกคำแปลที่ถูกต้อง ตอบถูก +10 ตอบผิด -5 กดปุ่ม "ถัดไป" เพื่อข้ามไปคำต่อไปได้เลย!',
            contentEn: 'Set 2 features 200+ intermediate-advanced words. Listen and match!'
        },
        {
            type: 'vocab_game',
            title: 'Vocabulary Listening Mastery — Set 2',
            words: [
                { word: 'Abolish', mean: 'ยกเลิก, ล้มเลิก' },
                { word: 'Absorb', mean: 'ดูดซับ, ซึมซับ' },
                { word: 'Abstract', mean: 'นามธรรม, บทคัดย่อ' },
                { word: 'Absurd', mean: 'ไร้สาระ, เหลวไหล' },
                { word: 'Accommodate', mean: 'รองรับ, จัดที่พักให้' },
                { word: 'Accompany', mean: 'ไปเป็นเพื่อน, ร่วมทาง' },
                { word: 'Accomplish', mean: 'ทำสำเร็จ, บรรลุ' },
                { word: 'Accurate', mean: 'ถูกต้อง, แม่นยำ' },
                { word: 'Accuse', mean: 'กล่าวหา, ฟ้องร้อง' },
                { word: 'Acquire', mean: 'ได้มา, ซื้อ' },
                { word: 'Adapt', mean: 'ปรับตัว, ดัดแปลง' },
                { word: 'Adhere', mean: 'ยึดมั่น, ติดแน่น' },
                { word: 'Adjacent', mean: 'อยู่ติดกัน, ข้างเคียง' },
                { word: 'Admire', mean: 'ชื่นชม, ยกย่อง' },
                { word: 'Adopt', mean: 'รับเลี้ยง, นำมาใช้' },
                { word: 'Adverse', mean: 'ไม่พึงประสงค์, เป็นปฏิปักษ์' },
                { word: 'Aesthetic', mean: 'เกี่ยวกับความงาม' },
                { word: 'Affirm', mean: 'ยืนยัน' },
                { word: 'Aggregate', mean: 'รวมกัน, ผลรวม' },
                { word: 'Agitate', mean: 'ปลุกปั่น, กระวนกระวาย' },
                { word: 'Allegation', mean: 'ข้อกล่าวหา' },
                { word: 'Alliance', mean: 'พันธมิตร' },
                { word: 'Allocate', mean: 'จัดสรร, แบ่งสัน' },
                { word: 'Alter', mean: 'เปลี่ยนแปลง, ดัดแปลง' },
                { word: 'Amateur', mean: 'มือสมัครเล่น' },
                { word: 'Amend', mean: 'แก้ไข, ปรับปรุง' },
                { word: 'Ample', mean: 'เพียงพอ, กว้างขวาง' },
                { word: 'Annex', mean: 'ผนวก, ส่วนต่อเติม' },
                { word: 'Annihilate', mean: 'ทำลายล้าง' },
                { word: 'Anonymous', mean: 'ไม่ระบุชื่อ, นิรนาม' },
                { word: 'Apparatus', mean: 'เครื่องมือ, อุปกรณ์' },
                { word: 'Apprehend', mean: 'จับกุม, เข้าใจ' },
                { word: 'Arbitrary', mean: 'ตามอำเภอใจ' },
                { word: 'Archive', mean: 'คลังเอกสาร, เก็บถาวร' },
                { word: 'Articulate', mean: 'พูดชัดเจน, เชื่อมต่อ' },
                { word: 'Aspire', mean: 'ปรารถนา, มุ่งหวัง' },
                { word: 'Assault', mean: 'ทำร้ายร่างกาย, โจมตี' },
                { word: 'Assert', mean: 'ยืนยัน, กล่าวอ้าง' },
                { word: 'Attain', mean: 'บรรลุ, ได้มา' },
                { word: 'Audit', mean: 'ตรวจสอบบัญชี' },
                { word: 'Authorize', mean: 'อนุมัติ, ให้อำนาจ' },
                { word: 'Autonomous', mean: 'เป็นอิสระ, ปกครองตนเอง' },
                { word: 'Avert', mean: 'หลีกเลี่ยง, ป้องกัน' },
                { word: 'Baffle', mean: 'ทำให้งุนงง' },
                { word: 'Bankrupt', mean: 'ล้มละลาย' },
                { word: 'Bargain', mean: 'ต่อรอง, ของถูก' },
                { word: 'Betray', mean: 'ทรยศ, หักหลัง' },
                { word: 'Bewilder', mean: 'ทำให้สับสน' },
                { word: 'Bizarre', mean: 'แปลกประหลาด' },
                { word: 'Bland', mean: 'จืดชืด, ไม่น่าสนใจ' },
                { word: 'Blaze', mean: 'ไฟลุกโชน, เปลวไฟ' },
                { word: 'Bliss', mean: 'ความสุขล้นเหลือ' },
                { word: 'Bloom', mean: 'เบ่งบาน, ออกดอก' },
                { word: 'Blunder', mean: 'ข้อผิดพลาดร้ายแรง' },
                { word: 'Boast', mean: 'คุยโม้, อวดอ้าง' },
                { word: 'Bold', mean: 'กล้าหาญ, โดดเด่น' },
                { word: 'Boost', mean: 'เพิ่ม, กระตุ้น' },
                { word: 'Bound', mean: 'ผูกมัด, ขอบเขต' },
                { word: 'Breach', mean: 'การละเมิด, รอยแตก' },
                { word: 'Brief', mean: 'สั้น, กระชับ' },
                { word: 'Brilliant', mean: 'ฉลาดมาก, เจิดจ้า' },
                { word: 'Burden', mean: 'ภาระ' },
                { word: 'Bureau', mean: 'สำนักงาน, กอง' },
                { word: 'Bureaucracy', mean: 'ระบบราชการ' },
                { word: 'Campaign', mean: 'การรณรงค์' },
                { word: 'Capable', mean: 'มีความสามารถ' },
                { word: 'Captivate', mean: 'ดึงดูดใจ, หลงใหล' },
                { word: 'Casualty', mean: 'ผู้บาดเจ็บ/เสียชีวิต' },
                { word: 'Cease', mean: 'หยุด, ยุติ' },
                { word: 'Census', mean: 'สำมะโนประชากร' },
                { word: 'Certify', mean: 'รับรอง, ให้การรับรอง' },
                { word: 'Challenge', mean: 'ท้าทาย, ความท้าทาย' },
                { word: 'Chronicle', mean: 'บันทึกเหตุการณ์' },
                { word: 'Chronic', mean: 'เรื้อรัง' },
                { word: 'Circulate', mean: 'หมุนเวียน, เผยแพร่' },
                { word: 'Cite', mean: 'อ้างอิง, กล่าวถึง' },
                { word: 'Civic', mean: 'เกี่ยวกับพลเมือง' },
                { word: 'Cling', mean: 'เกาะ, ยึดติด' },
                { word: 'Coherent', mean: 'สอดคล้องกัน, เข้าใจง่าย' },
                { word: 'Collapse', mean: 'พังทลาย, ล้มลง' },
                { word: 'Collide', mean: 'ชนกัน, ปะทะกัน' },
                { word: 'Commence', mean: 'เริ่มต้น' },
                { word: 'Compact', mean: 'กระชับ, กะทัดรัด' },
                { word: 'Companion', mean: 'เพื่อนร่วมทาง' },
                { word: 'Compel', mean: 'บังคับ, บีบบังคับ' },
                { word: 'Competent', mean: 'มีความสามารถ' },
                { word: 'Comply', mean: 'ปฏิบัติตาม' },
                { word: 'Compose', mean: 'แต่ง, ประกอบด้วย' },
                { word: 'Compound', mean: 'สารประกอบ, ผสม' },
                { word: 'Compulsory', mean: 'บังคับ, จำเป็น' },
                { word: 'Concede', mean: 'ยอมรับ, ยินยอม' },
                { word: 'Conceive', mean: 'คิดขึ้น, ตั้งครรภ์' },
                { word: 'Condemn', mean: 'ประณาม, ตำหนิ' },
                { word: 'Condense', mean: 'ย่อ, ทำให้ข้น' },
                { word: 'Conduct', mean: 'ดำเนินการ, ความประพฤติ' },
                { word: 'Confess', mean: 'สารภาพ' },
                { word: 'Confine', mean: 'จำกัด, กักขัง' },
                { word: 'Confirm', mean: 'ยืนยัน' },
                { word: 'Conflict', mean: 'ความขัดแย้ง' },
                { word: 'Conform', mean: 'ปฏิบัติตาม, สอดคล้อง' },
                { word: 'Confront', mean: 'เผชิญหน้า' },
                { word: 'Congest', mean: 'แออัด, คับคั่ง' },
                { word: 'Conquer', mean: 'พิชิต, เอาชนะ' },
                { word: 'Consent', mean: 'ยินยอม, อนุญาต' },
                { word: 'Conserve', mean: 'อนุรักษ์, ประหยัด' },
                { word: 'Conspicuous', mean: 'เด่นชัด, สะดุดตา' },
                { word: 'Constitute', mean: 'ประกอบด้วย, จัดตั้ง' },
                { word: 'Constrain', mean: 'บังคับ, จำกัด' },
                { word: 'Consult', mean: 'ปรึกษา, หารือ' },
                { word: 'Consume', mean: 'บริโภค, ใช้หมด' },
                { word: 'Contaminate', mean: 'ปนเปื้อน' },
                { word: 'Contemplate', mean: 'ครุ่นคิด, ไตร่ตรอง' },
                { word: 'Contend', mean: 'แข่งขัน, อ้างว่า' },
                { word: 'Context', mean: 'บริบท' },
                { word: 'Contract', mean: 'สัญญา, หดตัว' },
                { word: 'Contribute', mean: 'มีส่วนช่วย, บริจาค' },
                { word: 'Controversy', mean: 'ความขัดแย้ง, ข้อถกเถียง' },
                { word: 'Convene', mean: 'เรียกประชุม' },
                { word: 'Conventional', mean: 'ตามแบบแผน, ธรรมดา' },
                { word: 'Converge', mean: 'มาบรรจบกัน' },
                { word: 'Convey', mean: 'สื่อสาร, ลำเลียง' },
                { word: 'Convict', mean: 'ตัดสินว่าผิด, นักโทษ' },
                { word: 'Cooperate', mean: 'ให้ความร่วมมือ' },
                { word: 'Coordinate', mean: 'ประสานงาน' },
                { word: 'Cope', mean: 'รับมือ, จัดการ' },
                { word: 'Corpse', mean: 'ศพ' },
                { word: 'Correlate', mean: 'มีความสัมพันธ์กัน' },
                { word: 'Corrupt', mean: 'ทุจริต, เสื่อมเสีย' },
                { word: 'Cosmic', mean: 'เกี่ยวกับจักรวาล' },
                { word: 'Counsel', mean: 'ให้คำปรึกษา' },
                { word: 'Counterpart', mean: 'คู่เทียบ, ผู้ที่ดำรงตำแหน่งเดียวกัน' },
                { word: 'Courageous', mean: 'กล้าหาญ' },
                { word: 'Courtesy', mean: 'ความสุภาพ, มารยาท' },
                { word: 'Craft', mean: 'งานฝีมือ, ทักษะ' },
                { word: 'Credible', mean: 'น่าเชื่อถือ' },
                { word: 'Critique', mean: 'บทวิจารณ์' },
                { word: 'Crude', mean: 'หยาบ, ดิบ' },
                { word: 'Cumulative', mean: 'สะสม, เพิ่มพูน' },
                { word: 'Curb', mean: 'ควบคุม, จำกัด' },
                { word: 'Curious', mean: 'อยากรู้อยากเห็น' },
                { word: 'Currency', mean: 'สกุลเงิน' },
                { word: 'Curriculum', mean: 'หลักสูตร' },
                { word: 'Cynical', mean: 'เหยียดหยาม, ถากถาง' },
                { word: 'Dazzle', mean: 'ทำให้ตื่นตาตื่นใจ' },
                { word: 'Debate', mean: 'โต้วาที, ถกเถียง' },
                { word: 'Decay', mean: 'เสื่อมสภาพ, ผุพัง' },
                { word: 'Deceive', mean: 'หลอกลวง' },
                { word: 'Decent', mean: 'เหมาะสม, สุภาพ' },
                { word: 'Declare', mean: 'ประกาศ, แถลง' },
                { word: 'Decline', mean: 'ลดลง, ปฏิเสธ' },
                { word: 'Dedicate', mean: 'อุทิศ, ทุ่มเท' },
                { word: 'Deem', mean: 'ถือว่า, เห็นว่า' },
                { word: 'Defeat', mean: 'เอาชนะ, ความพ่ายแพ้' },
                { word: 'Defer', mean: 'เลื่อนออกไป, ยอมตาม' },
                { word: 'Deficit', mean: 'ขาดดุล, ส่วนที่ขาด' },
                { word: 'Defy', mean: 'ท้าทาย, ขัดขืน' },
                { word: 'Degrade', mean: 'ลดระดับ, ทำให้เสื่อมเสีย' },
                { word: 'Delegate', mean: 'มอบหมาย, ผู้แทน' },
                { word: 'Deliberate', mean: 'จงใจ, ไตร่ตรอง' },
                { word: 'Delicate', mean: 'บอบบาง, ละเอียดอ่อน' },
                { word: 'Delight', mean: 'ความยินดี, ทำให้พอใจ' },
                { word: 'Deliver', mean: 'ส่งมอบ, นำส่ง' },
                { word: 'Demand', mean: 'เรียกร้อง, ความต้องการ' },
                { word: 'Democracy', mean: 'ประชาธิปไตย' },
                { word: 'Demolish', mean: 'ทำลาย, รื้อถอน' },
                { word: 'Dense', mean: 'หนาแน่น' },
                { word: 'Deny', mean: 'ปฏิเสธ' },
                { word: 'Depict', mean: 'พรรณนา, วาดภาพ' },
                { word: 'Deplete', mean: 'ทำให้หมดสิ้น' },
                { word: 'Deploy', mean: 'ส่งกำลัง, นำไปใช้งาน' },
                { word: 'Deposit', mean: 'ฝากเงิน, เงินมัดจำ' },
                { word: 'Depress', mean: 'ทำให้หดหู่, กดลง' },
                { word: 'Deprive', mean: 'ลิดรอน, พราก' },
                { word: 'Derive', mean: 'ได้มาจาก' },
                { word: 'Descend', mean: 'ลงมา, สืบเชื้อสาย' },
                { word: 'Deserve', mean: 'สมควรได้รับ' },
                { word: 'Designate', mean: 'กำหนด, แต่งตั้ง' },
                { word: 'Desire', mean: 'ความปรารถนา' },
                { word: 'Despair', mean: 'ความสิ้นหวัง' },
                { word: 'Detach', mean: 'แยกออก, ถอดออก' },
                { word: 'Detect', mean: 'ตรวจจับ, สืบพบ' },
                { word: 'Deter', mean: 'ยับยั้ง, ขัดขวาง' },
                { word: 'Deteriorate', mean: 'เสื่อมลง, ทรุดโทรม' },
                { word: 'Devise', mean: 'คิดค้น, ประดิษฐ์' },
                { word: 'Devote', mean: 'อุทิศ, ทุ่มเท' },
                { word: 'Diagnose', mean: 'วินิจฉัย' },
                { word: 'Digest', mean: 'ย่อยอาหาร, ทำความเข้าใจ' },
                { word: 'Dignity', mean: 'ศักดิ์ศรี, ความสง่างาม' },
                { word: 'Diligent', mean: 'ขยันขันแข็ง' },
                { word: 'Diploma', mean: 'ประกาศนียบัตร' },
                { word: 'Diplomat', mean: 'นักการทูต' },
                { word: 'Discard', mean: 'ทิ้ง, ละทิ้ง' },
                { word: 'Discipline', mean: 'วินัย, ลงโทษ' },
                { word: 'Disclose', mean: 'เปิดเผย' },
                { word: 'Discord', mean: 'ความไม่ลงรอย' },
                { word: 'Discourse', mean: 'การสนทนา, วาทกรรม' },
                { word: 'Discrete', mean: 'แยกจากกัน, ไม่ต่อเนื่อง' },
                { word: 'Discriminate', mean: 'เลือกปฏิบัติ, แยกแยะ' },
                { word: 'Dismiss', mean: 'ไล่ออก, ยกฟ้อง' },
                { word: 'Disorder', mean: 'ความผิดปกติ, ความวุ่นวาย' },
                { word: 'Dispatch', mean: 'ส่งไป, จัดส่ง' },
                { word: 'Disperse', mean: 'กระจาย, สลาย' },
                { word: 'Displace', mean: 'ทำให้พลัดถิ่น' },
                { word: 'Dispose', mean: 'กำจัด, จัดการ' },
                { word: 'Dispute', mean: 'ข้อพิพาท, โต้แย้ง' },
                { word: 'Disrupt', mean: 'รบกวน, หยุดชะงัก' },
                { word: 'Dissolve', mean: 'ละลาย, ยุบ' },
                { word: 'Distort', mean: 'บิดเบือน' },
                { word: 'Distract', mean: 'ทำให้ไขว้เขว' },
                { word: 'Distribute', mean: 'กระจาย, แจกจ่าย' },
                { word: 'Disturb', mean: 'รบกวน, กวนใจ' }
            ]
        }
    ]
});
