LESSONS.push({
    id: 41,
    part: 1,
    isGame: true,
    titleTh: 'เก็งข้อสอบ Listening ชุดที่ 1',
    titleEn: 'Exam Prediction: Listening Set 1',
    icon: '🎯',
    sections: [
        {
            type: 'intro',
            title: '🎯 เก็งข้อสอบ Listening ชุดที่ 1',
            contentTh: 'จำลองข้อสอบ Listening แบบเก็งข้อสอบ! ทุกข้อมีให้ฟังเสียง + Transcript + คำแปลไทย + เฉลยละเอียด กดฟังก่อน แล้วค่อยตอบ เหมือนสอบจริง!',
            contentEn: 'Practice CU-TEP Listening with full audio, transcripts, Thai translations, and detailed explanations.',
            bullets: ['กดฟังเสียงก่อนตอบทุกข้อ 🔊', 'มีคำแปลไทยให้ทุกข้อ', 'เฉลยละเอียดทั้งไทยและอังกฤษ']
        },
        {
            type: 'quiz',
            title: '🎧 Listening Prediction (15 ข้อ)',
            questions: [
                { audio: 'Woman: I\'m thinking of dropping Professor Lee\'s chemistry class.\nMan: I wouldn\'t do that if I were you. It gets easier after the midterm.\nQuestion: What does the man suggest?', transcript: 'Woman: I\'m thinking of dropping Professor Lee\'s chemistry class.\nMan: I wouldn\'t do that if I were you. It gets easier after the midterm.', question: 'What does the man suggest?', questionTh: 'ผู้ชายแนะนำอะไร?\n\n💬 คำแปล: ผู้หญิง: ฉันกำลังคิดจะดรอปวิชาเคมีของอาจารย์ลี / ผู้ชาย: ถ้าเป็นฉันจะไม่ทำอย่างนั้นนะ มันจะง่ายขึ้นหลังสอบกลางภาค', choices: ['She should drop the class immediately.', 'She should stay in the class because it will improve.', 'She should talk to Professor Lee.', 'She should study harder for the midterm.'], answer: 1, explanationTh: '"I wouldn\'t do that if I were you" = ถ้าเป็นฉัน ฉันจะไม่ทำ (แนะนำให้อยู่ต่อ) + "It gets easier after the midterm" = มันจะง่ายขึ้นหลังมิดเทอม', explanationEn: 'He advises against dropping the class because it improves after midterm.' },
                { audio: 'Man: Did Sarah end up getting the promotion?\nWoman: Far from it. She didn\'t even make the shortlist.\nQuestion: What happened to Sarah?', transcript: 'Man: Did Sarah end up getting the promotion?\nWoman: Far from it. She didn\'t even make the shortlist.', question: 'What happened to Sarah?', questionTh: 'เกิดอะไรขึ้นกับ Sarah?\n\n💬 คำแปล: ผู้ชาย: สุดท้าย Sarah ได้เลื่อนตำแหน่งไหม? / ผู้หญิง: ห่างไกลมาก เธอไม่ได้เข้ารอบคัดเลือกด้วยซ้ำ', choices: ['She got the promotion.', 'She was not even considered for the promotion.', 'She turned down the promotion.', 'She was shortlisted but lost.'], answer: 1, explanationTh: '"Far from it" = ห่างไกลมาก (ตรงข้ามเลย) + "didn\'t even make the shortlist" = ไม่ได้เข้ารอบสั้นด้วยซ้ำ', explanationEn: '"Far from it" means the opposite happened. She was not even shortlisted.' },
                { audio: 'Woman: How was the concert last night?\nMan: Don\'t get me started. The lead singer was completely off-key the whole time.\nQuestion: How does the man feel about the concert?', transcript: 'Woman: How was the concert last night?\nMan: Don\'t get me started. The lead singer was completely off-key.', question: 'How does the man feel about the concert?', questionTh: 'ผู้ชายรู้สึกอย่างไรกับคอนเสิร์ต?\n\n💬 คำแปล: ผู้หญิง: คอนเสิร์ตเมื่อคืนเป็นไง? / ผู้ชาย: อย่าให้เริ่มพูดเลย นักร้องนำร้องเพี้ยนตลอดทั้งงาน', choices: ['He thoroughly enjoyed it.', 'He was very disappointed.', 'He thought it was average.', 'He left before it ended.'], answer: 1, explanationTh: '"Don\'t get me started" = อย่าให้เริ่มพูดเลย (บ่นเรื่องนี้ได้ยาว) + "off-key" = ร้องเพี้ยน → ผิดหวังมาก', explanationEn: '"Don\'t get me started" expresses frustration. "Off-key" means singing out of tune.' },
                { audio: 'Man: I\'m sorry, but the manager isn\'t available at the moment.\nWoman: Could you ask her to return my call when she\'s free?\nQuestion: What does the woman want?', transcript: 'Man: The manager isn\'t available.\nWoman: Could you ask her to return my call?', question: 'What does the woman want?', questionTh: 'ผู้หญิงต้องการอะไร?\n\n💬 คำแปล: ผู้ชาย: ขอโทษครับ ผู้จัดการไม่ว่างตอนนี้ / ผู้หญิง: ช่วยบอกเธอให้โทรกลับหาฉันได้ไหมเมื่อเธอว่าง?', choices: ['She wants to wait for the manager.', 'She wants the manager to call her back.', 'She wants to leave a written message.', 'She wants to speak to someone else.'], answer: 1, explanationTh: '"return my call" = โทรกลับหาฉัน', explanationEn: '"Return my call" means to call back.' },
                { audio: 'Woman: I heard the new Thai restaurant downtown is to die for.\nMan: Really? We should check it out this weekend.\nQuestion: What does the woman mean about the restaurant?', transcript: 'Woman: The new Thai restaurant is to die for.\nMan: We should check it out.', question: 'What does the woman mean?', questionTh: 'ผู้หญิงหมายความว่าอย่างไรเกี่ยวกับร้านอาหาร?\n\n💬 คำแปล: ผู้หญิง: ฉันได้ยินว่าร้านอาหารไทยใหม่ในตัวเมืองอร่อยสุดยอดเลย / ผู้ชาย: จริงเหรอ? เราควรไปลองสุดสัปดาห์นี้', choices: ['The restaurant is dangerous.', 'The restaurant is extremely good.', 'The restaurant has closed down.', 'The restaurant is too expensive.'], answer: 1, explanationTh: 'สำนวน "to die for" = ดีมากๆ สุดยอด (ไม่ได้เกี่ยวกับความตาย)', explanationEn: '"To die for" is an idiom meaning something is extremely good or desirable.' },
                { audio: 'Man: Professor, may I hand in my paper a day late? My printer broke down.\nWoman: I\'m afraid that\'s not possible. The deadline is firm.\nQuestion: What does the professor mean?', transcript: 'Man: May I hand in my paper a day late?\nWoman: I\'m afraid that\'s not possible. The deadline is firm.', question: 'What does the professor mean?', questionTh: 'อาจารย์หมายความว่าอย่างไร?\n\n💬 คำแปล: ผู้ชาย: อาจารย์ครับ ผมขอส่งรายงานช้าไปหนึ่งวันได้ไหมครับ เครื่องพิมพ์พัง / ผู้หญิง: ฉันเกรงว่าจะไม่ได้ค่ะ เส้นตายนี้เปลี่ยนไม่ได้', choices: ['She will accept the late paper.', 'She will not extend the deadline.', 'She will fix his printer.', 'She will give him extra time.'], answer: 1, explanationTh: '"I\'m afraid that\'s not possible" = เกรงว่าจะไม่ได้ + "The deadline is firm" = เส้นตายเปลี่ยนไม่ได้', explanationEn: 'She clearly refuses, stating the deadline cannot be changed.' },
                { audio: 'Woman: Have you finished reading the novel for tomorrow\'s book club?\nMan: I\'ve barely scratched the surface. I only started it yesterday.\nQuestion: How much of the novel has the man read?', transcript: 'Woman: Have you finished the novel?\nMan: I\'ve barely scratched the surface.', question: 'How much has the man read?', questionTh: 'ผู้ชายอ่านหนังสือไปมากแค่ไหน?\n\n💬 คำแปล: ผู้หญิง: อ่านนิยายสำหรับชมรมหนังสือพรุ่งนี้จบยัง? / ผู้ชาย: แทบจะยังไม่ได้ขีดข่วนผิวเลย ฉันเพิ่งเริ่มอ่านเมื่อวาน', choices: ['He has finished the whole book.', 'He has read almost nothing.', 'He has read about half.', 'He has read the surface of the book only.'], answer: 1, explanationTh: 'สำนวน "barely scratched the surface" = แทบจะยังไม่ได้เริ่ม / ทำได้นิดเดียว', explanationEn: '"Barely scratched the surface" means he has done very little; he has only just begun.' },
                { audio: 'Man: I can\'t believe they\'re tearing down the old library.\nWoman: I know, right? That building has been there for over a century.\nQuestion: What is happening to the old library?', transcript: 'Man: They\'re tearing down the old library.\nWoman: That building has been there for over a century.', question: 'What is happening to the library?', questionTh: 'เกิดอะไรขึ้นกับห้องสมุดเก่า?\n\n💬 คำแปล: ผู้ชาย: ไม่อยากเชื่อเลยว่าพวกเขาจะทุบห้องสมุดเก่า / ผู้หญิง: ใช่สิ อาคารนั้นอยู่มากว่าศตวรรษแล้วนะ', choices: ['It is being renovated.', 'It is being demolished.', 'It is being moved.', 'It is being expanded.'], answer: 1, explanationTh: '"tearing down" = รื้อทุบทิ้ง = demolished', explanationEn: '"Tearing down" means demolishing or destroying a building.' },
                { audio: 'Woman: The meeting has been pushed back to 3 PM.\nMan: That actually works out better for me.\nQuestion: What happened to the meeting?', transcript: 'Woman: The meeting has been pushed back to 3 PM.\nMan: That works out better for me.', question: 'What happened to the meeting?', questionTh: 'เกิดอะไรขึ้นกับการประชุม?\n\n💬 คำแปล: ผู้หญิง: การประชุมถูกเลื่อนไปเป็น 3 โมง / ผู้ชาย: จริงๆ แล้วเวลานั้นสะดวกกว่าสำหรับฉันเลย', choices: ['It was cancelled.', 'It was rescheduled to a later time.', 'It was moved to an earlier time.', 'It was shortened.'], answer: 1, explanationTh: '"pushed back" = เลื่อนออกไป (ไปเวลาที่ช้ากว่าเดิม)', explanationEn: '"Pushed back" means postponed to a later time.' },
                { audio: 'Man: Should we take the highway or the back roads?\nWoman: Let\'s take the back roads. I\'d rather enjoy the scenery than sit in traffic.\nQuestion: Why does the woman prefer the back roads?', transcript: 'Man: Highway or back roads?\nWoman: Let\'s take the back roads. I\'d rather enjoy the scenery than sit in traffic.', question: 'Why does the woman prefer back roads?', questionTh: 'ทำไมผู้หญิงถึงชอบถนนสายรอง?\n\n💬 คำแปล: ผู้ชาย: เราควรใช้ทางด่วนหรือถนนสายรอง? / ผู้หญิง: ไปทางสายรองเถอะ ฉันอยากชมวิวมากกว่านั่งรถติด', choices: ['The back roads are faster.', 'She wants to see the scenery and avoid traffic.', 'The highway is closed.', 'The back roads are shorter.'], answer: 1, explanationTh: '"enjoy the scenery" = ชมวิว + "than sit in traffic" = มากกว่านั่งรถติด', explanationEn: 'She prefers the scenic route over being stuck in traffic.' },
                { audio: 'Woman: How\'s the new intern doing?\nMan: She\'s a quick learner. She\'s already got the hang of the filing system.\nQuestion: What does the man say about the intern?', transcript: 'Woman: How\'s the new intern?\nMan: She\'s a quick learner. She\'s got the hang of the filing system.', question: 'What does the man say about the intern?', questionTh: 'ผู้ชายพูดเกี่ยวกับพนักงานฝึกงานว่าอย่างไร?\n\n💬 คำแปล: ผู้หญิง: พนักงานฝึกงานคนใหม่เป็นไงบ้าง? / ผู้ชาย: เธอเรียนรู้เร็วมาก เธอเริ่มเข้าใจระบบจัดเก็บเอกสารแล้ว', choices: ['She is struggling with her tasks.', 'She is adapting well and learning fast.', 'She has been fired.', 'She needs more training on filing.'], answer: 1, explanationTh: '"quick learner" = เรียนรู้เร็ว + "got the hang of" = เริ่มเข้าใจ/ชำนาญแล้ว', explanationEn: '"Quick learner" and "got the hang of" both indicate she is adapting well.' },
                { audio: 'Man: I\'m going to have to burn the midnight oil to finish this project.\nWoman: Don\'t overdo it. You need to take care of your health too.\nQuestion: What is the man planning to do?', transcript: 'Man: I\'m going to burn the midnight oil.\nWoman: Don\'t overdo it.', question: 'What is the man planning to do?', questionTh: 'ผู้ชายวางแผนจะทำอะไร?\n\n💬 คำแปล: ผู้ชาย: ฉันต้องเผาน้ำมันเที่ยงคืน (นั่งทำงานดึก) เพื่อทำโปรเจคนี้ให้เสร็จ / ผู้หญิง: อย่าหักโหมนะ คุณต้องดูแลสุขภาพด้วย', choices: ['Set something on fire.', 'Work late into the night.', 'Buy more oil.', 'Go to bed early.'], answer: 1, explanationTh: 'สำนวน "burn the midnight oil" = นั่งทำงานดึก ทำงานจนดึกมาก', explanationEn: '"Burn the midnight oil" means to work late into the night.' },
                { audio: 'Woman: Did you hear that the company is downsizing?\nMan: Yes, and word has it that our department might be affected.\nQuestion: What does the man mean?', transcript: 'Woman: The company is downsizing.\nMan: Word has it that our department might be affected.', question: 'What does the man mean?', questionTh: 'ผู้ชายหมายความว่าอย่างไร?\n\n💬 คำแปล: ผู้หญิง: ได้ยินไหมว่าบริษัทกำลังลดขนาด? / ผู้ชาย: ใช่ แล้วก็มีข่าวลือว่าแผนกเราอาจจะโดนด้วย', choices: ['Their department will definitely close.', 'There are rumors their department could be impacted.', 'He is not worried at all.', 'The company is expanding.'], answer: 1, explanationTh: '"word has it" = มีข่าวว่า/มีเสียงลือว่า + "might be affected" = อาจจะได้รับผลกระทบ', explanationEn: '"Word has it" means there is a rumor. "Might be affected" expresses possibility.' },
                { audio: 'Man: I think we should call it a day. Everyone looks exhausted.\nWoman: Good idea. We can pick up where we left off tomorrow.\nQuestion: What does the man suggest?', transcript: 'Man: We should call it a day.\nWoman: We can pick up where we left off tomorrow.', question: 'What does the man suggest?', questionTh: 'ผู้ชายเสนออะไร?\n\n💬 คำแปล: ผู้ชาย: ฉันคิดว่าเราควรเลิกทำวันนี้ ทุกคนดูเหนื่อยมาก / ผู้หญิง: ความคิดดี เราสามารถทำต่อจากตรงที่เราค้างไว้พรุ่งนี้', choices: ['They should work overtime.', 'They should stop working for today.', 'They should call someone.', 'They should start a new project.'], answer: 1, explanationTh: '"call it a day" = เลิกทำวันนี้ หยุดพักได้แล้ว + "pick up where we left off" = ทำต่อจากตรงที่ค้างไว้', explanationEn: '"Call it a day" means to stop working. "Pick up where we left off" means to continue from where they stopped.' },
                { audio: 'Woman: Excuse me, is this seat taken?\nMan: No, go ahead. Make yourself comfortable.\nQuestion: What does the man mean?', transcript: 'Woman: Is this seat taken?\nMan: No, go ahead. Make yourself comfortable.', question: 'What does the man mean?', questionTh: 'ผู้ชายหมายความว่าอย่างไร?\n\n💬 คำแปล: ผู้หญิง: ขอโทษค่ะ ที่นั่งนี้มีคนนั่งไหม? / ผู้ชาย: ไม่ครับ เชิญเลย นั่งตามสบายครับ', choices: ['The seat is reserved for someone.', 'She is free to sit there.', 'He wants her to leave.', 'The seat is broken.'], answer: 1, explanationTh: '"go ahead" = เชิญเลย + "make yourself comfortable" = นั่งตามสบาย', explanationEn: '"Go ahead" gives permission and "make yourself comfortable" is an invitation to sit.' }
            ]
        }
    ]
});
