LESSONS.push({
    id: 42,
    part: 1,
    isGame: true,
    titleTh: 'เก็งข้อสอบ Listening ชุดที่ 2',
    titleEn: 'Exam Prediction: Listening Set 2',
    icon: '🎯',
    sections: [
        {
            type: 'intro',
            title: '🎯 เก็งข้อสอบ Listening ชุดที่ 2',
            contentTh: 'ชุดที่ 2 เน้นสำนวน ความหมายแฝง และ Short Talks (ประกาศ/โฆษณา) แบบจำลองข้อสอบจริง',
            contentEn: 'Set 2 focuses on idioms, implied meanings, and short talks.',
            bullets: ['กดฟังเสียงก่อนตอบทุกข้อ 🔊', 'มีคำแปลไทยให้ทุกข้อ', 'ข้อ 11-15 เป็น Short Talks (ประกาศ)']
        },
        {
            type: 'quiz',
            title: '🎧 Listening Prediction Set 2 (15 ข้อ)',
            questions: [
                { audio: 'Man: I just got the electricity bill. It\'s through the roof!\nWoman: We should probably start turning off lights when we leave rooms.\nQuestion: What does the man mean?', transcript: 'Man: The electricity bill is through the roof!\nWoman: We should start turning off lights.', question: 'What does the man mean?', questionTh: 'ผู้ชายหมายความว่าอย่างไร?\n\n💬 คำแปล: ผู้ชาย: ฉันเพิ่งได้บิลค่าไฟ มันแพงทะลุหลังคาเลย! / ผู้หญิง: เราน่าจะเริ่มปิดไฟเมื่อออกจากห้อง', choices: ['The bill was very low.', 'The bill was extremely high.', 'The roof needs repair.', 'The lights are broken.'], answer: 1, explanationTh: '"through the roof" = สูงมาก พุ่งขึ้นอย่างมาก (ค่าไฟแพงมาก)', explanationEn: '"Through the roof" means extremely high.' },
                { audio: 'Woman: Tom was supposed to pick me up an hour ago.\nMan: That\'s so like him. He\'s always running behind schedule.\nQuestion: What does the man imply about Tom?', transcript: 'Woman: Tom was supposed to pick me up an hour ago.\nMan: That\'s so like him. He\'s always running behind schedule.', question: 'What does the man imply?', questionTh: 'ผู้ชายสื่ออะไรเกี่ยวกับ Tom?\n\n💬 คำแปล: ผู้หญิง: Tom ควรจะมารับฉันตั้งแต่ชั่วโมงที่แล้ว / ผู้ชาย: เหมือน Tom เลย เขาล่าช้าอยู่เสมอ', choices: ['Tom is usually punctual.', 'Tom is habitually late.', 'Tom forgot about the plan.', 'Tom is running somewhere.'], answer: 1, explanationTh: '"That\'s so like him" = เหมือนนิสัยเขาเลย + "running behind schedule" = ช้ากว่ากำหนด = ชอบสายเป็นนิสัย', explanationEn: '"So like him" means it is typical behavior. He is habitually late.' },
                { audio: 'Man: Did you manage to get through to the customer service hotline?\nWoman: I was on hold for forty minutes and then gave up.\nQuestion: What happened?', transcript: 'Man: Did you get through to customer service?\nWoman: I was on hold for forty minutes and gave up.', question: 'What happened?', questionTh: 'เกิดอะไรขึ้น?\n\n💬 คำแปล: ผู้ชาย: โทรถึงสายด่วนบริการลูกค้าไหม? / ผู้หญิง: ฉันรอสายอยู่ 40 นาทีแล้วก็ยอมแพ้', choices: ['She spoke to a representative.', 'She waited too long and hung up without speaking to anyone.', 'She called back later.', 'She visited the office in person.'], answer: 1, explanationTh: '"on hold" = รอสาย + "gave up" = ยอมแพ้ = เธอไม่ได้คุยกับใครเลย', explanationEn: 'She waited on hold for 40 minutes and gave up without getting through.' },
                { audio: 'Woman: I have mixed feelings about moving to a new city.\nMan: Change can be scary, but it might be the fresh start you need.\nQuestion: How does the woman feel?', transcript: 'Woman: I have mixed feelings about moving.\nMan: Change can be scary but might be a fresh start.', question: 'How does the woman feel?', questionTh: 'ผู้หญิงรู้สึกอย่างไร?\n\n💬 คำแปล: ผู้หญิง: ฉันมีความรู้สึกปนกันเกี่ยวกับการย้ายไปเมืองใหม่ / ผู้ชาย: การเปลี่ยนแปลงอาจน่ากลัว แต่มันอาจเป็นจุดเริ่มต้นใหม่ที่คุณต้องการ', choices: ['She is completely against moving.', 'She has both positive and negative feelings about it.', 'She is extremely excited to move.', 'She has already decided not to move.'], answer: 1, explanationTh: '"mixed feelings" = ความรู้สึกปนกัน ทั้งดีและไม่ดี ยังตัดสินใจไม่ได้', explanationEn: '"Mixed feelings" means she has both positive and negative emotions about it.' },
                { audio: 'Man: Can I borrow your laptop for a minute? Mine just died.\nWoman: Sure, but I need it back in ten minutes. I have a deadline.\nQuestion: What will the woman do?', transcript: 'Man: Can I borrow your laptop? Mine died.\nWoman: Sure, but I need it back in ten minutes.', question: 'What will the woman do?', questionTh: 'ผู้หญิงจะทำอะไร?\n\n💬 คำแปล: ผู้ชาย: ขอยืมแล็ปท็อปสักครู่ได้ไหม? ของฉันพังไปแล้ว / ผู้หญิง: ได้ แต่ฉันต้องใช้คืนภายใน 10 นาทีนะ ฉันมีเดดไลน์', choices: ['Refuse to lend her laptop.', 'Lend it briefly but needs it back soon.', 'Give it to him permanently.', 'Buy him a new laptop.'], answer: 1, explanationTh: '"Sure, but I need it back in ten minutes" = ให้ยืมได้แต่ต้องคืนเร็วๆ', explanationEn: 'She agrees to lend it but with a time limit of 10 minutes.' },
                { audio: 'Woman: The new employee seems to rub everyone the wrong way.\nMan: Give him time. He\'s just trying too hard to impress.\nQuestion: What does the woman say about the new employee?', transcript: 'Woman: The new employee rubs everyone the wrong way.\nMan: Give him time. He\'s trying too hard to impress.', question: 'What does the woman say?', questionTh: 'ผู้หญิงพูดเกี่ยวกับพนักงานใหม่ว่าอย่างไร?\n\n💬 คำแปล: ผู้หญิง: พนักงานใหม่ดูเหมือนจะทำให้ทุกคนหงุดหงิด / ผู้ชาย: ให้เวลาเขาหน่อย เขาแค่พยายามสร้างความประทับใจมากเกินไป', choices: ['He is very popular.', 'He annoys or irritates people.', 'He is extremely shy.', 'He rubs people\'s backs.'], answer: 1, explanationTh: '"rub someone the wrong way" = ทำให้คนอื่นรู้สึกหงุดหงิด/ไม่พอใจ', explanationEn: '"Rub someone the wrong way" means to irritate or annoy people.' },
                { audio: 'Man: I\'ve been going back and forth about whether to take the job overseas.\nWoman: Have you made a pros and cons list?\nQuestion: What is the man\'s problem?', transcript: 'Man: I\'ve been going back and forth about the overseas job.\nWoman: Have you made a pros and cons list?', question: 'What is the man\'s problem?', questionTh: 'ปัญหาของผู้ชายคืออะไร?\n\n💬 คำแปล: ผู้ชาย: ฉันลังเลไปมาว่าจะรับงานต่างประเทศดีไหม / ผู้หญิง: เคยทำรายการข้อดีข้อเสียหรือยัง?', choices: ['He lost his job.', 'He cannot decide whether to accept an overseas position.', 'He is afraid of flying.', 'He does not like his current job.'], answer: 1, explanationTh: '"going back and forth" = ลังเลไปมา ตัดสินใจไม่ได้', explanationEn: '"Going back and forth" means being unable to decide; hesitating between options.' },
                { audio: 'Woman: My presentation is in two hours and I still haven\'t finished my slides.\nMan: You\'d better get cracking then!\nQuestion: What does the man suggest?', transcript: 'Woman: My presentation is in two hours.\nMan: You\'d better get cracking!', question: 'What does the man suggest?', questionTh: 'ผู้ชายแนะนำอะไร?\n\n💬 คำแปล: ผู้หญิง: การนำเสนอของฉันอีก 2 ชั่วโมงและยังทำสไลด์ไม่เสร็จ / ผู้ชาย: คุณควรจะรีบลงมือทำเดี๋ยวนี้เลย!', choices: ['She should cancel the presentation.', 'She should start working on it immediately.', 'She should crack the slides.', 'She should ask someone else to present.'], answer: 1, explanationTh: '"get cracking" = รีบลงมือทำเดี๋ยวนี้เลย! เร่งมือ!', explanationEn: '"Get cracking" means to start working immediately and quickly.' },
                { audio: 'Man: That job interview was a piece of cake.\nWoman: Lucky you! Mine was incredibly stressful.\nQuestion: How does the man feel about his interview?', transcript: 'Man: The interview was a piece of cake.\nWoman: Lucky you! Mine was stressful.', question: 'How does the man feel?', questionTh: 'ผู้ชายรู้สึกอย่างไรกับการสัมภาษณ์?\n\n💬 คำแปล: ผู้ชาย: สัมภาษณ์งานนั้นง่ายเหมือนปอกกล้วยเข้าปาก / ผู้หญิง: โชคดีจัง! ของฉันเครียดมาก', choices: ['It was very difficult.', 'It was very easy.', 'He ate cake during the interview.', 'He was nervous.'], answer: 1, explanationTh: '"a piece of cake" = ง่ายมาก ง่ายเหมือนปอกกล้วยเข้าปาก', explanationEn: '"A piece of cake" is an idiom meaning something is very easy.' },
                { audio: 'Woman: Did you hear? The company just landed a multi-million dollar contract!\nMan: No wonder the boss has been in such a good mood lately.\nQuestion: What happened?', transcript: 'Woman: The company landed a multi-million dollar contract!\nMan: No wonder the boss is in a good mood.', question: 'What happened?', questionTh: 'เกิดอะไรขึ้น?\n\n💬 คำแปล: ผู้หญิง: ได้ยินไหม? บริษัทเพิ่งได้สัญญามูลค่าหลายล้านดอลลาร์! / ผู้ชาย: ไม่แปลกใจเลยที่เจ้านายอารมณ์ดีช่วงนี้', choices: ['The company lost money.', 'The company won a very large contract.', 'The boss resigned.', 'The company moved offices.'], answer: 1, explanationTh: '"landed a contract" = ได้รับสัญญา/ดีลสำเร็จ + "No wonder" = ไม่แปลกใจเลย', explanationEn: '"Landed a contract" means successfully obtained a deal. "No wonder" means it explains something.' },
                { audio: 'Announcement: Attention shoppers. The store will be closing in fifteen minutes. Please bring your final selections to the checkout counter. Thank you for shopping with us today.\nQuestion: Where is this announcement most likely heard?', transcript: 'The store will be closing in fifteen minutes. Please bring your final selections to the checkout counter.', question: 'Where is this announcement heard?', questionTh: 'ประกาศนี้น่าจะได้ยินที่ไหน?\n\n💬 คำแปล: แจ้งลูกค้าทราบ ร้านจะปิดภายใน 15 นาที กรุณานำสินค้าที่เลือกไปยังเคาน์เตอร์ชำระเงิน ขอบคุณที่มาช้อปปิ้งกับเราวันนี้', choices: ['At an airport.', 'At a department store or supermarket.', 'At a school.', 'At a hospital.'], answer: 1, explanationTh: 'คำสำคัญ: "shoppers", "selections", "checkout counter" = ลูกค้า, สินค้า, เคาน์เตอร์จ่ายเงิน → ห้างสรรพสินค้า/ซูเปอร์มาร์เก็ต', explanationEn: 'Keywords like "shoppers", "selections", and "checkout counter" indicate a retail store.' },
                { audio: 'Announcement: Good evening, ladies and gentlemen. Flight BA247 to London Heathrow has been delayed by approximately two hours due to adverse weather conditions. We apologize for the inconvenience. Complimentary refreshments will be available at Gate 12.\nQuestion: What is the purpose of this announcement?', transcript: 'Flight BA247 to London has been delayed by two hours due to weather. Complimentary refreshments at Gate 12.', question: 'What is the purpose of this announcement?', questionTh: 'จุดประสงค์ของประกาศนี้คืออะไร?\n\n💬 คำแปล: สุภาพบุรุษและสุภาพสตรี เที่ยวบิน BA247 ไปลอนดอนฮีทโธรว์ล่าช้าประมาณ 2 ชั่วโมงเนื่องจากสภาพอากาศเลวร้าย ขออภัยในความไม่สะดวก เครื่องดื่มฟรีที่ประตู 12', choices: ['To announce a new flight route.', 'To inform passengers of a flight delay and offer refreshments.', 'To cancel the flight permanently.', 'To ask passengers to board immediately.'], answer: 1, explanationTh: 'ประกาศแจ้งเรื่องเที่ยวบินล่าช้า (delayed) + เสนอเครื่องดื่มฟรี (complimentary refreshments)', explanationEn: 'The announcement informs about a delay and offers complimentary refreshments.' },
                { audio: 'Announcement: Welcome to the National History Museum. Today\'s guided tour will begin in the Egyptian Gallery on the second floor in approximately ten minutes. Please note that photography is permitted, but flash photography and tripods are strictly prohibited in all exhibition halls.\nQuestion: What are visitors NOT allowed to do?', transcript: 'Guided tour begins in the Egyptian Gallery, second floor, in ten minutes. Flash photography and tripods are prohibited.', question: 'What are visitors NOT allowed to do?', questionTh: 'ผู้เข้าชมไม่ได้รับอนุญาตให้ทำอะไร?\n\n💬 คำแปล: ยินดีต้อนรับสู่พิพิธภัณฑ์ประวัติศาสตร์แห่งชาติ ทัวร์นำชมวันนี้จะเริ่มที่แกลเลอรีอียิปต์ชั้น 2 ในอีกประมาณ 10 นาที โปรดทราบว่าอนุญาตให้ถ่ายรูปได้ แต่ห้ามใช้แฟลชและขาตั้งกล้องในทุกห้องนิทรรศการ', choices: ['Take photos.', 'Use flash and tripods.', 'Visit the Egyptian Gallery.', 'Join the guided tour.'], answer: 1, explanationTh: '"photography is permitted" = ถ่ายรูปได้ แต่ "flash photography and tripods are strictly prohibited" = ห้ามใช้แฟลชและขาตั้งกล้อง', explanationEn: 'Photography is allowed, but flash and tripods are strictly prohibited.' },
                { audio: 'Announcement: Attention all employees. Due to scheduled maintenance, the elevator in Building C will be out of service from 9 AM to 5 PM this Friday. Please use the stairwell or the elevator in Building B as an alternative. We apologize for any inconvenience.\nQuestion: What should employees do this Friday?', transcript: 'Building C elevator out of service Friday 9AM-5PM. Use stairwell or Building B elevator.', question: 'What should employees do?', questionTh: 'พนักงานควรทำอะไรในวันศุกร์นี้?\n\n💬 คำแปล: แจ้งพนักงานทุกท่าน เนื่องจากการบำรุงรักษาตามกำหนด ลิฟต์ในอาคาร C จะหยุดให้บริการตั้งแต่ 9 โมงเช้าถึง 5 โมงเย็นวันศุกร์นี้ กรุณาใช้บันไดหรือลิฟต์ในอาคาร B แทน ขออภัยในความไม่สะดวก', choices: ['Avoid Building C entirely.', 'Use stairs or the elevator in Building B instead.', 'Work from home on Friday.', 'Report the elevator problem to maintenance.'], answer: 1, explanationTh: 'ประกาศบอกให้ใช้บันไดหรือลิฟต์อาคาร B แทน', explanationEn: 'The announcement tells employees to use the stairwell or Building B elevator as alternatives.' },
                { audio: 'Announcement: Your attention please. The 4:15 express train to Osaka will be departing from Platform 7, not Platform 3 as previously announced. I repeat, the 4:15 express to Osaka now departs from Platform 7. We apologize for the change.\nQuestion: What is the announcement about?', transcript: 'The 4:15 express to Osaka departs from Platform 7, not Platform 3 as previously announced.', question: 'What is the announcement about?', questionTh: 'ประกาศนี้เกี่ยวกับอะไร?\n\n💬 คำแปล: ขอความสนใจ รถไฟด่วน 4:15 ไปโอซาก้าจะออกจากชานชาลา 7 ไม่ใช่ชานชาลา 3 ตามที่ประกาศไว้ก่อนหน้า ขอย้ำ รถไฟด่วน 4:15 ไปโอซาก้าออกจากชานชาลา 7 ขออภัยในการเปลี่ยนแปลง', choices: ['A train cancellation.', 'A platform change for a train departure.', 'A new train schedule.', 'A ticket price increase.'], answer: 1, explanationTh: 'ประกาศแจ้งเปลี่ยนชานชาลา (Platform change) จาก 3 เป็น 7', explanationEn: 'The announcement informs passengers of a platform change from 3 to 7.' }
            ]
        }
    ]
});
