LESSONS.push({
    id: 99,
    part: 1,
    isGame: true,
    titleTh: 'เกมส์จับคู่คำศัพท์ ชุดที่ 1',
    titleEn: 'Vocab Listening Match Game — Set 1',
    icon: '🔥',
    sections: [
        {
            type: 'intro',
            title: 'กติกาการเล่น (How to play)',
            contentTh: 'เกมนี้มีคลังคำศัพท์ CU-TEP มากกว่า 100 คำ! ระบบจะสุ่มคำศัพท์มาให้คุณฟัง (กดที่รูปลำโพง 🔊) จากนั้นให้คุณเลือกความหมายที่ถูกต้องจาก 4 ตัวเลือก หากตอบถูกจะได้ 10 คะแนน และเกมจะสุ่มคำต่อไปมาให้ทันที เล่นไปเรื่อยๆ จนกว่าคุณจะจำได้ทุกคำ!',
            contentEn: 'Listen to the vocabulary word and choose the correct Thai meaning. The game is endless, and the words are randomly selected from our massive dictionary.'
        },
        {
            type: 'vocab_game',
            title: 'Vocabulary Listening Mastery',
            words: [
                { word: 'Abandon', mean: 'ละทิ้ง, ปล่อย' },
                { word: 'Abundant', mean: 'มากมาย, อุดมสมบูรณ์' },
                { word: 'Accelerate', mean: 'เร่งความเร็ว' },
                { word: 'Accumulate', mean: 'สะสม, เพิ่มพูน' },
                { word: 'Acknowledge', mean: 'ยอมรับ, รับรู้' },
                { word: 'Adequate', mean: 'เพียงพอ' },
                { word: 'Advocate', mean: 'สนับสนุน, ทนายความ' },
                { word: 'Alleviate', mean: 'บรรเทา, ทำให้น้อยลง' },
                { word: 'Ambiguous', mean: 'กำกวม, คลุมเครือ' },
                { word: 'Ambitious', mean: 'ทะเยอทะยาน' },
                { word: 'Analyze', mean: 'วิเคราะห์' },
                { word: 'Anticipate', mean: 'คาดหวัง, ทำนาย' },
                { word: 'Apparent', mean: 'ชัดเจน, ปรากฏให้เห็น' },
                { word: 'Assess', mean: 'ประเมิน' },
                { word: 'Attribute', mean: 'คุณลักษณะ, ถือว่าเป็นของ' },
                { word: 'Authentic', mean: 'ของแท้, น่าเชื่อถือ' },
                { word: 'Beneficial', mean: 'เป็นประโยชน์' },
                { word: 'Bias', mean: 'อคติ, ลำเอียง' },
                { word: 'Catastrophe', mean: 'ภัยพิบัติ, ความหายนะ' },
                { word: 'Clarify', mean: 'ทำให้ชัดเจน' },
                { word: 'Coincidence', mean: 'ความบังเอิญ' },
                { word: 'Collaborate', mean: 'ร่วมมือกัน' },
                { word: 'Commence', mean: 'เริ่มต้น' },
                { word: 'Compensate', mean: 'ชดเชย, ทดแทน' },
                { word: 'Compile', mean: 'รวบรวม, เรียบเรียง' },
                { word: 'Complicated', mean: 'ซับซ้อน' },
                { word: 'Comprehensive', mean: 'ครอบคลุม, สมบูรณ์' },
                { word: 'Conceal', mean: 'ปกปิด, ซ่อนเร้น' },
                { word: 'Conclude', mean: 'สรุป' },
                { word: 'Consequence', mean: 'ผลที่ตามมา' },
                { word: 'Considerable', mean: 'มากมาย, สำคัญ' },
                { word: 'Consistent', mean: 'สม่ำเสมอ, สอดคล้องกัน' },
                { word: 'Contradict', mean: 'ขัดแย้ง, โต้แย้ง' },
                { word: 'Crucial', mean: 'สำคัญมาก, วิกฤต' },
                { word: 'Cultivate', mean: 'เพาะปลูก, อบรม' },
                { word: 'Deficient', mean: 'บกพร่อง, ขาดแคลน' },
                { word: 'Demonstrate', mean: 'สาธิต, แสดงให้เห็น' },
                { word: 'Desperate', mean: 'สิ้นหวัง, เข้าตาจน' },
                { word: 'Determine', mean: 'ตัดสินใจ, กำหนด' },
                { word: 'Devastating', mean: 'ทำลายล้าง, น่าตกใจ' },
                { word: 'Dilemma', mean: 'สภาวะกลืนไม่เข้าคายไม่ออก' },
                { word: 'Diminish', mean: 'ลดลง, ทำให้เล็กลง' },
                { word: 'Discrepancy', mean: 'ความคลาดเคลื่อน, ความแตกต่าง' },
                { word: 'Distinguish', mean: 'แยกแยะ, ทำให้เห็นความแตกต่าง' },
                { word: 'Diversify', mean: 'ทำให้หลากหลาย' },
                { word: 'Drastic', mean: 'รุนแรง, ร้ายแรง' },
                { word: 'Efficient', mean: 'มีประสิทธิภาพ' },
                { word: 'Eliminate', mean: 'กำจัด, ขจัด' },
                { word: 'Emerge', mean: 'ปรากฏขึ้น, โผล่ออกมา' },
                { word: 'Emphasize', mean: 'เน้นย้ำ, ให้ความสำคัญ' },
                { word: 'Encounter', mean: 'เผชิญหน้า, พบเจอ' },
                { word: 'Endeavor', mean: 'ความพยายาม' },
                { word: 'Enormous', mean: 'ใหญ่โต, มโหฬาร' },
                { word: 'Ensure', mean: 'ทำให้แน่ใจ, รับรอง' },
                { word: 'Essential', mean: 'จำเป็น, สำคัญ' },
                { word: 'Establish', mean: 'ก่อตั้ง, สร้าง' },
                { word: 'Evaluate', mean: 'ประเมินผล' },
                { word: 'Evidence', mean: 'หลักฐาน' },
                { word: 'Exaggerate', mean: 'พูดเกินจริง' },
                { word: 'Examine', mean: 'ตรวจสอบ, ทดสอบ' },
                { word: 'Exceed', mean: 'เกินกว่า, มากกว่า' },
                { word: 'Exhausted', mean: 'เหน็ดเหนื่อย, หมดแรง' },
                { word: 'Expand', mean: 'ขยาย' },
                { word: 'Expertise', mean: 'ความเชี่ยวชาญ' },
                { word: 'Fascinating', mean: 'น่าหลงใหล, น่าทึ่ง' },
                { word: 'Fatal', mean: 'ถึงแก่ชีวิต, ร้ายแรง' },
                { word: 'Flaw', mean: 'ข้อบกพร่อง, ตำหนิ' },
                { word: 'Fluctuate', mean: 'ผันผวน, ขึ้นๆลงๆ' },
                { word: 'Formulate', mean: 'กำหนดรูปแบบ, วางกฎเกณฑ์' },
                { word: 'Fragile', mean: 'เปราะบาง, แตกหักง่าย' },
                { word: 'Generate', mean: 'สร้างขึ้น, ผลิต' },
                { word: 'Genuine', mean: 'แท้จริง, บริสุทธิ์ใจ' },
                { word: 'Hazard', mean: 'อันตราย' },
                { word: 'Hesitate', mean: 'ลังเล' },
                { word: 'Hostile', mean: 'เป็นศัตรู, ไม่เป็นมิตร' },
                { word: 'Identify', mean: 'ระบุตัวตน, ชี้แนะ' },
                { word: 'Ignorant', mean: 'เพิกเฉย, ไม่มีความรู้' },
                { word: 'Illustrate', mean: 'อธิบายให้เห็นภาพ' },
                { word: 'Immense', mean: 'กว้างใหญ่, มหาศาล' },
                { word: 'Imply', mean: 'บอกใบ้, สื่อความหมาย' },
                { word: 'Implement', mean: 'นำไปปฏิบัติ, ทำให้เกิดผล' },
                { word: 'Indicate', mean: 'บ่งชี้, แสดงให้เห็น' },
                { word: 'Inevitable', mean: 'หลีกเลี่ยงไม่ได้' },
                { word: 'Inquisitive', mean: 'อยากรู้อยากเห็น' },
                { word: 'Inspire', mean: 'สร้างแรงบันดาลใจ' },
                { word: 'Integrate', mean: 'ผสมผสาน, รวมเข้าด้วยกัน' },
                { word: 'Intense', mean: 'รุนแรง, เข้มข้น' },
                { word: 'Interfere', mean: 'แทรกแซง, รบกวน' },
                { word: 'Interpret', mean: 'ตีความ, แปลความหมาย' },
                { word: 'Investigate', mean: 'สืบสวน, ตรวจสอบ' },
                { word: 'Isolate', mean: 'แยกตัวออก, โดดเดี่ยว' },
                { word: 'Jeopardize', mean: 'ทำให้ตกอยู่ในอันตราย' },
                { word: 'Legitimate', mean: 'ถูกต้องตามกฎหมาย, สมเหตุสมผล' },
                { word: 'Lucrative', mean: 'ได้กำไรดี' },
                { word: 'Maintain', mean: 'รักษาไว้, บำรุง' },
                { word: 'Mandatory', mean: 'เป็นการบังคับ, ข้อบังคับ' },
                { word: 'Manipulate', mean: 'ควบคุม, จัดการ (ในทางไม่ดี)' },
                { word: 'Modify', mean: 'ดัดแปลง, แก้ไข' },
                { word: 'Navigate', mean: 'นำทาง, หาทาง' },
                { word: 'Neglect', mean: 'ละเลย, ทอดทิ้ง' },
                { word: 'Negotiate', mean: 'เจรจาต่อรอง' },
                { word: 'Notorious', mean: 'มีชื่อเสียงในทางไม่ดี' },
                { word: 'Obese', mean: 'อ้วนเกินไป' },
                { word: 'Objective', mean: 'วัตถุประสงค์, ยุติธรรม' },
                { word: 'Obligation', mean: 'ข้อผูกมัด, หน้าที่' },
                { word: 'Obscure', mean: 'กำกวม, คลุมเครือ, ปิดบัง' },
                { word: 'Observe', mean: 'สังเกต' },
                { word: 'Obsolete', mean: 'ล้าสมัย, เลิกใช้แล้ว' },
                { word: 'Obstacle', mean: 'อุปสรรค' },
                { word: 'Occupy', mean: 'ครอบครอง, อยู่อาศัย' },
                { word: 'Optimum', mean: 'เหมาะสมที่สุด, ดีที่สุด' },
                { word: 'Outrageous', mean: 'รุนแรง, น่าตกใจ, เกินกว่าเหตุ' },
                { word: 'Participate', mean: 'มีส่วนร่วม, เข้าร่วม' },
                { word: 'Perceive', mean: 'รับรู้, เข้าใจ' },
                { word: 'Persevere', mean: 'พยายาม, อุตสาหะ' },
                { word: 'Persuade', mean: 'ชักชวน, โน้มน้าว' },
                { word: 'Phenomenon', mean: 'ปรากฏการณ์' },
                { word: 'Plausible', mean: 'เป็นไปได้, สมเหตุสมผล' },
                { word: 'Potential', mean: 'ศักยภาพ, ความเป็นไปได้' },
                { word: 'Precious', mean: 'ล้ำค่า, มีค่า' },
                { word: 'Precise', mean: 'แม่นยำ, ชัดเจน' },
                { word: 'Predict', mean: 'ทำนาย, พยากรณ์' },
                { word: 'Prejudice', mean: 'อคติ, ความลำเอียง' },
                { word: 'Preliminary', mean: 'ขั้นต้น, เบื้องต้น' },
                { word: 'Preserve', mean: 'อนุรักษ์, สงวน' },
                { word: 'Prestige', mean: 'ชื่อเสียง, เกียรติยศ' },
                { word: 'Prevent', mean: 'ป้องกัน, ขัดขวาง' },
                { word: 'Primary', mean: 'เบื้องต้น, สำคัญที่สุด' },
                { word: 'Principle', mean: 'หลักการ, กฎ' },
                { word: 'Prior', mean: 'ก่อนหน้านี้' },
                { word: 'Probable', mean: 'น่าจะเป็นไปได้' },
                { word: 'Procedure', mean: 'ขั้นตอน, ระเบียบการ' },
                { word: 'Proceed', mean: 'ดำเนินการต่อ, ก้าวหน้า' },
                { word: 'Profound', mean: 'ลึกซึ้ง, สำคัญ' },
                { word: 'Prohibit', mean: 'ห้าม, ไม่อนุญาต' },
                { word: 'Prominent', mean: 'โดดเด่น, มีชื่อเสียง' },
                { word: 'Promote', mean: 'ส่งเสริม, เลื่อนตำแหน่ง' },
                { word: 'Proportion', mean: 'สัดส่วน' },
                { word: 'Propose', mean: 'เสนอ, ขอแต่งงาน' },
                { word: 'Prospect', mean: 'โอกาส, ความหวัง' },
                { word: 'Prosper', mean: 'เจริญรุ่งเรือง' },
                { word: 'Protect', mean: 'ปกป้อง, คุ้มครอง' },
                { word: 'Prove', mean: 'พิสูจน์' },
                { word: 'Provoke', mean: 'ยั่วยุ, ทำให้โกรธ' },
                { word: 'Punctual', mean: 'ตรงต่อเวลา' },
                { word: 'Purchase', mean: 'ซื้อ' },
                { word: 'Purpose', mean: 'จุดประสงค์' },
                { word: 'Pursue', mean: 'ติดตาม, ไล่ตาม' },
                { word: 'Qualify', mean: 'มีคุณสมบัติเหมาะสม' },
                { word: 'Quantity', mean: 'ปริมาณ' },
                { word: 'Radical', mean: 'รุนแรง, อย่างถอนรากถอนโคน' },
                { word: 'Random', mean: 'สุ่ม, ไม่เจาะจง' },
                { word: 'Rapid', mean: 'รวดเร็ว' },
                { word: 'Rational', mean: 'มีเหตุผล' },
                { word: 'Realize', mean: 'ตระหนัก, เข้าใจ' },
                { word: 'Reasonable', mean: 'สมเหตุสมผล' },
                { word: 'Rebel', mean: 'กบฏ, ขัดขืน' },
                { word: 'Recall', mean: 'จำได้, นึกถึง' },
                { word: 'Recognize', mean: 'จำได้, ยอมรับ' },
                { word: 'Recommend', mean: 'แนะนำ' },
                { word: 'Recover', mean: 'ฟื้นตัว, หายป่วย' },
                { word: 'Reduce', mean: 'ลดลง' },
                { word: 'Refer', mean: 'อ้างถึง' },
                { word: 'Reflect', mean: 'สะท้อนให้เห็น' },
                { word: 'Reform', mean: 'ปฏิรูป, ปรับปรุง' },
                { word: 'Refuse', mean: 'ปฏิเสธ' },
                { word: 'Regard', mean: 'พิจารณา, เอาใจใส่' },
                { word: 'Region', mean: 'ภูมิภาค, บริเวณ' },
                { word: 'Register', mean: 'ลงทะเบียน' },
                { word: 'Regulate', mean: 'ควบคุม, จัดระเบียบ' },
                { word: 'Reject', mean: 'ปฏิเสธ' },
                { word: 'Relate', mean: 'เกี่ยวข้อง, เชื่อมโยง' },
                { word: 'Relative', mean: 'ญาติ, สัมพัทธ์' },
                { word: 'Relax', mean: 'ผ่อนคลาย' },
                { word: 'Release', mean: 'ปล่อยตัว, เผยแพร่' },
                { word: 'Relevant', mean: 'ที่เกี่ยวข้อง' },
                { word: 'Reliable', mean: 'เชื่อถือได้' },
                { word: 'Relieve', mean: 'บรรเทา, ผ่อนคลาย' },
                { word: 'Reluctant', mean: 'ไม่เต็มใจ, ลังเล' },
                { word: 'Rely', mean: 'พึ่งพา, ไว้ใจ' },
                { word: 'Remain', mean: 'ยังคงอยู่, เหลืออยู่' },
                { word: 'Remark', mean: 'ข้อสังเกต, สังเกตเห็น' },
                { word: 'Remedy', mean: 'วิธีรักษา, ยารักษา' },
                { word: 'Remember', mean: 'จำได้' },
                { word: 'Remind', mean: 'เตือนความจำ' },
                { word: 'Remote', mean: 'ห่างไกล' },
                { word: 'Remove', mean: 'เอาออก, กำจัด' },
                { word: 'Renew', mean: 'ต่ออายุ, ทำใหม่' },
                { word: 'Repair', mean: 'ซ่อมแซม' },
                { word: 'Replace', mean: 'แทนที่' },
                { word: 'Reply', mean: 'ตอบกลับ' },
                { word: 'Report', mean: 'รายงาน' },
                { word: 'Represent', mean: 'เป็นตัวแทน' },
                { word: 'Request', mean: 'ขอร้อง' },
                { word: 'Require', mean: 'ต้องการ, บังคับ' },
                { word: 'Rescue', mean: 'ช่วยเหลือ, กู้ภัย' },
                { word: 'Research', mean: 'การวิจัย' },
                { word: 'Resemble', mean: 'คล้ายคลึง' },
                { word: 'Resent', mean: 'โกรธเคือง' },
                { word: 'Reserve', mean: 'จอง, สงวน' },
                { word: 'Reside', mean: 'อยู่อาศัย' },
                { word: 'Resign', mean: 'ลาออก' },
                { word: 'Resist', mean: 'ต่อต้าน, ต้านทาน' },
                { word: 'Resolve', mean: 'แก้ปัญหา, ตัดสินใจแน่วแน่' },
                { word: 'Resource', mean: 'ทรัพยากร' },
                { word: 'Respect', mean: 'เคารพ' },
                { word: 'Respond', mean: 'ตอบสนอง' },
                { word: 'Responsible', mean: 'มีความรับผิดชอบ' },
                { word: 'Restore', mean: 'ฟื้นฟู' },
                { word: 'Restrict', mean: 'จำกัด' },
                { word: 'Result', mean: 'ผลลัพธ์' },
                { word: 'Retain', mean: 'เก็บไว้, รักษาไว้' },
                { word: 'Retire', mean: 'เกษียณ' },
                { word: 'Reveal', mean: 'เปิดเผย' },
                { word: 'Revenue', mean: 'รายได้' },
                { word: 'Reverse', mean: 'ย้อนกลับ, ถอยหลัง' },
                { word: 'Review', mean: 'ทบทวน, วิจารณ์' },
                { word: 'Revise', mean: 'แก้ไข, ทบทวน' },
                { word: 'Revive', mean: 'ฟื้นฟู, ทำให้มีชีวิตใหม่' },
                { word: 'Reward', mean: 'รางวัล' },
                { word: 'Ridiculous', mean: 'ไร้สาระ, น่าขัน' },
                { word: 'Rigid', mean: 'เข้มงวด, แข็ง' },
                { word: 'Risk', mean: 'ความเสี่ยง' },
                { word: 'Rival', mean: 'คู่แข่ง' },
                { word: 'Robust', mean: 'แข็งแรง, ทนทาน' },
                { word: 'Ruin', mean: 'ทำลาย, ความพินาศ' },
                { word: 'Sacrifice', mean: 'เสียสละ' },
                { word: 'Salary', mean: 'เงินเดือน' },
                { word: 'Sanction', mean: 'การคว่ำบาตร, การอนุมัติ' },
                { word: 'Satisfy', mean: 'ทำให้พอใจ' },
                { word: 'Scale', mean: 'ขนาด, มาตราส่วน' },
                { word: 'Scarce', mean: 'ขาดแคลน, หายาก' },
                { word: 'Scatter', mean: 'กระจาย, โปรย' },
                { word: 'Schedule', mean: 'ตารางเวลา' },
                { word: 'Scheme', mean: 'แผนการ, โครงการ' },
                { word: 'Scholar', mean: 'นักวิชาการ' },
                { word: 'Search', mean: 'ค้นหา' },
                { word: 'Secure', mean: 'ปลอดภัย, มั่นคง' },
                { word: 'Seek', mean: 'ค้นหา, แสวงหา' },
                { word: 'Select', mean: 'เลือก' },
                { word: 'Sensitive', mean: 'อ่อนไหว' },
                { word: 'Sentence', mean: 'ประโยค, คำพิพากษา' },
                { word: 'Separate', mean: 'แยกออก' },
                { word: 'Sequence', mean: 'ลำดับ' },
                { word: 'Serious', mean: 'จริงจัง, รุนแรง' },
                { word: 'Serve', mean: 'ให้บริการ, รับใช้' },
                { word: 'Settle', mean: 'ตั้งรกราก, จัดการ' },
                { word: 'Severe', mean: 'รุนแรง' },
                { word: 'Shallow', mean: 'ตื้น' },
                { word: 'Shame', mean: 'ความละอายใจ' },
                { word: 'Shape', mean: 'รูปร่าง' },
                { word: 'Share', mean: 'แบ่งปัน' },
                { word: 'Sharp', mean: 'แหลมคม, ฉลาด' },
                { word: 'Shelter', mean: 'ที่พักพิง' },
                { word: 'Shift', mean: 'เปลี่ยน, เคลื่อนย้าย' },
                { word: 'Shock', mean: 'ทำให้ตกใจ' },
                { word: 'Shrink', mean: 'หด' },
                { word: 'Sick', mean: 'ป่วย' },
                { word: 'Sight', mean: 'สายตา, การมองเห็น' },
                { word: 'Sign', mean: 'สัญญาณ, ลงนาม' },
                { word: 'Signal', mean: 'สัญญาณ' },
                { word: 'Significance', mean: 'ความสำคัญ' },
                { word: 'Silence', mean: 'ความเงียบ' },
                { word: 'Silly', mean: 'โง่เขลา, ไร้สาระ' },
                { word: 'Similar', mean: 'คล้ายคลึง' },
                { word: 'Simple', mean: 'เรียบง่าย' },
                { word: 'Sincere', mean: 'จริงใจ' },
                { word: 'Single', mean: 'เดี่ยว, โสด' },
                { word: 'Sink', mean: 'จม' },
                { word: 'Situation', mean: 'สถานการณ์' },
                { word: 'Size', mean: 'ขนาด' },
                { word: 'Skill', mean: 'ทักษะ' },
                { word: 'Skip', mean: 'ข้าม' },
                { word: 'Slight', mean: 'เล็กน้อย' },
                { word: 'Slip', mean: 'ลื่น' },
                { word: 'Slow', mean: 'ช้า' },
                { word: 'Small', mean: 'เล็ก' },
                { word: 'Smart', mean: 'ฉลาด' },
                { word: 'Smash', mean: 'ชน, ทำลาย' },
                { word: 'Smell', mean: 'กลิ่น' },
                { word: 'Smile', mean: 'รอยยิ้ม' },
                { word: 'Smooth', mean: 'ราบรื่น, เรียบ' },
                { word: 'Social', mean: 'ทางสังคม' },
                { word: 'Society', mean: 'สังคม' },
                { word: 'Soft', mean: 'นุ่ม' },
                { word: 'Soil', mean: 'ดิน' },
                { word: 'Solid', mean: 'ของแข็ง, แข็งแกร่ง' },
                { word: 'Solution', mean: 'ทางออก, วิธีแก้ปัญหา' },
                { word: 'Solve', mean: 'แก้ปัญหา' },
                { word: 'Source', mean: 'แหล่งที่มา' },
                { word: 'Space', mean: 'พื้นที่, อวกาศ' },
                { word: 'Spare', mean: 'สำรอง' },
                { word: 'Special', mean: 'พิเศษ' },
                { word: 'Specific', mean: 'เฉพาะเจาะจง' },
                { word: 'Spectacular', mean: 'น่าตื่นตาตื่นใจ' },
                { word: 'Speech', mean: 'สุนทรพจน์' },
                { word: 'Speed', mean: 'ความเร็ว' },
                { word: 'Spell', mean: 'สะกดคำ' },
                { word: 'Spend', mean: 'ใช้จ่าย, ใช้เวลา' },
                { word: 'Spirit', mean: 'จิตวิญญาณ' },
                { word: 'Split', mean: 'แยก, ผ่า' },
                { word: 'Spoil', mean: 'ทำให้เสีย, ตามใจจนเสียคน' },
                { word: 'Sponsor', mean: 'ผู้สนับสนุน' },
                { word: 'Spot', mean: 'จุด, สังเกตเห็น' },
                { word: 'Spread', mean: 'แพร่กระจาย' },
                { word: 'Spring', mean: 'ฤดูใบไม้ผลิ, กระโดด' },
                { word: 'Square', mean: 'สี่เหลี่ยมจัตุรัส' },
                { word: 'Squeeze', mean: 'บีบ, คั้น' },
                { word: 'Stable', mean: 'มั่นคง, เสถียร' },
                { word: 'Staff', mean: 'พนักงาน' },
                { word: 'Stage', mean: 'เวที, ขั้นตอน' },
                { word: 'Standard', mean: 'มาตรฐาน' },
                { word: 'Start', mean: 'เริ่มต้น' },
                { word: 'State', mean: 'รัฐ, สภาพ, กล่าว' },
                { word: 'Statement', mean: 'คำแถลง' }
            ]
        }
    ]
});
