LESSONS.push({
    id: 44,
    part: 1,
    isGame: true,
    titleTh: 'เก็งข้อสอบ Listening ชุดที่ 4',
    titleEn: 'Exam Prediction: Listening Set 4',
    icon: '🎯',
    sections: [
        {
            type: 'intro',
            title: '🎯 เก็งข้อสอบ Listening ชุดที่ 4',
            contentTh: 'ชุดที่ 4 เน้นสถานการณ์ในชีวิตจริง: ร้านอาหาร, ธนาคาร, โรงพยาบาล, มหาวิทยาลัย + Long Talks',
            contentEn: 'Set 4 focuses on real-life situations and longer talks.',
            bullets: ['ข้อ 1-10: สถานการณ์จริง (บริการ, การศึกษา, สุขภาพ)', 'ข้อ 11-15: Long Talks (ข่าว, สารคดี)', 'คำแปลไทยครบทุกข้อ']
        },
        {
            type: 'quiz',
            title: '🎧 Listening Prediction Set 4 (15 ข้อ)',
            questions: [
                { audio: 'Waiter: Are you ready to order, or do you need a few more minutes?\nCustomer: I\'m ready. I\'ll have the grilled salmon with a side salad, please.\nWaiter: Excellent choice. And for your drink?\nCustomer: Just water, thank you.\nQuestion: Where does this conversation take place?', transcript: 'Waiter: Ready to order?\nCustomer: Grilled salmon with a side salad. Water to drink.', question: 'Where does this take place?', questionTh: 'บทสนทนานี้เกิดขึ้นที่ไหน?\n\n💬 คำแปล: พนักงาน: พร้อมสั่งหรือยังครับ หรือต้องการเวลาอีกสักครู่? / ลูกค้า: พร้อมแล้วค่ะ ขอปลาแซลมอนย่างกับสลัดเคียง / พนักงาน: เลือกได้ดีครับ แล้วเครื่องดื่มล่ะครับ? / ลูกค้า: แค่น้ำเปล่าค่ะ ขอบคุณ', choices: ['At a grocery store.', 'At a restaurant.', 'At a hospital.', 'At a cooking class.'], answer: 1, explanationTh: 'คำสำคัญ: "order", "grilled salmon", "side salad", "drink" → ร้านอาหาร', explanationEn: 'Key words like "order", "grilled salmon", and "drink" indicate a restaurant.' },
                { audio: 'Teller: How can I help you today?\nCustomer: I\'d like to open a savings account.\nTeller: Sure. Do you have two forms of identification with you?\nCustomer: Yes, I have my passport and my driver\'s license.\nQuestion: What is the customer trying to do?', transcript: 'Customer wants to open a savings account. Teller asks for two IDs.', question: 'What is the customer doing?', questionTh: 'ลูกค้าต้องการทำอะไร?\n\n💬 คำแปล: พนักงาน: ให้ช่วยอะไรดีครับ? / ลูกค้า: ฉันอยากเปิดบัญชีออมทรัพย์ค่ะ / พนักงาน: ได้ครับ มีบัตรแสดงตน 2 ใบไหมครับ? / ลูกค้า: มีค่ะ มีพาสปอร์ตกับใบขับขี่', choices: ['Withdraw money.', 'Open a savings account.', 'Report a lost card.', 'Exchange currency.'], answer: 1, explanationTh: '"open a savings account" = เปิดบัญชีออมทรัพย์', explanationEn: 'She clearly states she wants to "open a savings account".' },
                { audio: 'Doctor: How long have you been experiencing these headaches?\nPatient: About two weeks now. They usually come in the afternoon.\nDoctor: Any other symptoms? Nausea, blurred vision?\nPatient: Some nausea, but no vision problems.\nQuestion: What is the patient\'s main complaint?', transcript: 'Patient has headaches for two weeks, usually afternoon. Some nausea, no vision problems.', question: 'What is the main complaint?', questionTh: 'อาการหลักของผู้ป่วยคืออะไร?\n\n💬 คำแปล: หมอ: ปวดหัวมานานแค่ไหนแล้ว? / ผู้ป่วย: ประมาณ 2 สัปดาห์แล้วครับ มักจะปวดตอนบ่าย / หมอ: มีอาการอื่นไหม? คลื่นไส้ ตาพร่ามัว? / ผู้ป่วย: คลื่นไส้บ้างครับ แต่ตาไม่มีปัญหา', choices: ['Blurred vision.', 'Persistent headaches.', 'Stomach pain.', 'Difficulty sleeping.'], answer: 1, explanationTh: 'อาการหลักคือปวดหัว (headaches) มา 2 สัปดาห์', explanationEn: 'The main complaint is recurring headaches over two weeks.' },
                { audio: 'Student: Excuse me, Professor. I missed last Thursday\'s lecture. Is there any way I can get the notes?\nProfessor: The slides are posted on the course website. But I\'d also recommend borrowing a classmate\'s handwritten notes.\nQuestion: What does the professor suggest?', transcript: 'Student missed Thursday\'s lecture. Professor says slides are online + borrow classmate\'s notes.', question: 'What does the professor suggest?', questionTh: 'อาจารย์แนะนำอะไร?\n\n💬 คำแปล: นักศึกษา: ขอโทษครับอาจารย์ ผมขาดเรียนวันพฤหัสที่แล้ว มีทางไหนจะได้โน้ตไหมครับ? / อาจารย์: สไลด์โพสต์ไว้บนเว็บไซต์วิชาแล้ว แต่แนะนำให้ยืมโน้ตที่เพื่อนจดด้วยนะ', choices: ['Attend a make-up class.', 'Check the website and borrow a classmate\'s notes.', 'Drop the course.', 'Email the professor for a private lesson.'], answer: 1, explanationTh: 'อาจารย์แนะนำ 2 อย่าง: ดูสไลด์บนเว็บ + ยืมโน้ตเพื่อน', explanationEn: 'The professor recommends checking online slides AND borrowing classmate notes.' },
                { audio: 'Receptionist: Grand Hotel, how may I assist you?\nCaller: I\'d like to make a reservation for two nights, checking in on December 15th.\nReceptionist: Certainly. Would you prefer a standard room or a deluxe suite?\nCaller: Standard is fine. What\'s the rate?\nReceptionist: It\'s three thousand five hundred baht per night, breakfast included.\nQuestion: How much will the caller pay in total?', transcript: 'Reservation: 2 nights from Dec 15. Standard room. 3,500 baht/night, breakfast included.', question: 'How much total?', questionTh: 'ผู้โทรจะต้องจ่ายทั้งหมดเท่าไร?\n\n💬 คำแปล: พนักงาน: โรงแรมแกรนด์ ให้ช่วยอะไรดีคะ? / ผู้โทร: อยากจองห้องพัก 2 คืน เช็คอินวันที่ 15 ธันวา / พนักงาน: ได้ค่ะ ต้องการห้องมาตรฐานหรือห้องดีลักซ์? / ผู้โทร: มาตรฐานก็ได้ ราคาเท่าไร? / พนักงาน: 3,500 บาทต่อคืนค่ะ รวมอาหารเช้า', choices: ['3,500 baht.', '7,000 baht.', '10,500 baht.', '5,000 baht.'], answer: 1, explanationTh: '3,500 บาท × 2 คืน = 7,000 บาท', explanationEn: '3,500 baht per night × 2 nights = 7,000 baht total.' },
                { audio: 'Woman: I\'m at my wit\'s end with this project. Nothing seems to be working.\nMan: Why don\'t you take a step back and look at the bigger picture?\nQuestion: What does the man suggest?', transcript: 'Woman: I\'m at my wit\'s end with this project.\nMan: Take a step back and look at the bigger picture.', question: 'What does the man suggest?', questionTh: 'ผู้ชายแนะนำอะไร?\n\n💬 คำแปล: ผู้หญิง: ฉันหมดปัญญากับโปรเจคนี้แล้ว ไม่มีอะไรได้ผลเลย / ผู้ชาย: ทำไมไม่ลองถอยออกมาดูภาพรวมล่ะ?', choices: ['Give up on the project.', 'Step back and consider the overall perspective.', 'Ask for a deadline extension.', 'Start the project from scratch.'], answer: 1, explanationTh: '"at my wit\'s end" = หมดปัญญา + "take a step back" = ถอยออกมา + "bigger picture" = ภาพรวม/มุมมองกว้างๆ', explanationEn: '"Take a step back" means to pause and reconsider. "Bigger picture" means the overall perspective.' },
                { audio: 'Man: The traffic was bumper to bumper this morning. It took me nearly an hour to get here.\nWoman: You should try the new expressway. It\'s much faster.\nQuestion: What was the man\'s problem?', transcript: 'Man: Traffic was bumper to bumper. Took nearly an hour.\nWoman: Try the new expressway.', question: 'What was the problem?', questionTh: 'ปัญหาของผู้ชายคืออะไร?\n\n💬 คำแปล: ผู้ชาย: รถติดแน่นขนัดเมื่อเช้า ใช้เวลาเกือบชั่วโมงกว่าจะมาถึง / ผู้หญิง: ลองใช้ทางด่วนใหม่สิ เร็วกว่าเยอะ', choices: ['His car broke down.', 'Heavy traffic made him arrive late.', 'He got lost.', 'The expressway was closed.'], answer: 1, explanationTh: '"bumper to bumper" = รถติดแน่นจนกันชนชนกัน = รถติดมาก', explanationEn: '"Bumper to bumper" means very heavy, slow-moving traffic.' },
                { audio: 'Woman: I can\'t make heads or tails of these instructions.\nMan: Let me have a look. Maybe two heads are better than one.\nQuestion: What does the woman mean?', transcript: 'Woman: I can\'t make heads or tails of these instructions.\nMan: Maybe two heads are better than one.', question: 'What does the woman mean?', questionTh: 'ผู้หญิงหมายความว่าอย่างไร?\n\n💬 คำแปล: ผู้หญิง: ฉันไม่เข้าใจคำสั่งเหล่านี้เลย / ผู้ชาย: ให้ฉันดูหน่อย สองหัวดีกว่าหัวเดียว', choices: ['She lost something.', 'She cannot understand the instructions at all.', 'She flipped a coin.', 'She read the instructions backward.'], answer: 1, explanationTh: '"can\'t make heads or tails" = ไม่เข้าใจเลย งงสับสน + "two heads are better than one" = คิดสองคนดีกว่าคนเดียว', explanationEn: '"Can\'t make heads or tails" means unable to understand something at all.' },
                { audio: 'Man: Are you coming to the farewell party for Mr. Chen on Friday?\nWoman: I wouldn\'t miss it for the world. He\'s been such a great mentor.\nQuestion: Will the woman attend the party?', transcript: 'Man: Coming to Mr. Chen\'s farewell party?\nWoman: I wouldn\'t miss it for the world.', question: 'Will the woman attend?', questionTh: 'ผู้หญิงจะไปงานไหม?\n\n💬 คำแปล: ผู้ชาย: คุณจะไปงานเลี้ยงอำลาคุณเฉินวันศุกร์ไหม? / ผู้หญิง: ฉันไม่มีวันพลาดเด็ดขาด เขาเป็นพี่เลี้ยงที่ดีมาก', choices: ['No, she has other plans.', 'Yes, she will definitely attend.', 'She is not sure yet.', 'She will attend only if she finishes work.'], answer: 1, explanationTh: '"wouldn\'t miss it for the world" = ไม่มีวันพลาดเด็ดขาด (จะไปแน่นอน 100%)', explanationEn: '"Wouldn\'t miss it for the world" means she will absolutely attend.' },
                { audio: 'Woman: The new policy has been a blessing in disguise. It actually made our workflow more efficient.\nMan: I guess every cloud has a silver lining.\nQuestion: What does the woman think about the new policy?', transcript: 'Woman: The new policy is a blessing in disguise. Workflow is more efficient.\nMan: Every cloud has a silver lining.', question: 'What does the woman think?', questionTh: 'ผู้หญิงคิดอย่างไรกับนโยบายใหม่?\n\n💬 คำแปล: ผู้หญิง: นโยบายใหม่เป็นเรื่องดีที่ซ่อนเร้น จริงๆ แล้วทำให้ขั้นตอนงานมีประสิทธิภาพขึ้น / ผู้ชาย: เหมือนกับว่าในทุกเมฆดำมีขอบสีเงิน', choices: ['It was entirely negative.', 'It seemed bad at first but turned out to be beneficial.', 'It had no effect on workflow.', 'It should be reversed immediately.'], answer: 1, explanationTh: '"blessing in disguise" = สิ่งดีที่ปลอมตัวมา (ดูแย่ตอนแรกแต่กลับดี) + "every cloud has a silver lining" = ในทุกวิกฤตมีโอกาส', explanationEn: '"Blessing in disguise" = something bad that turns out good. "Every cloud has a silver lining" = bad situations have positive aspects.' },
                { audio: 'News: In local news, the City Council has approved a thirty-million-baht budget for the construction of a new public park in the Sukhumvit area. The park, which will feature jogging paths, a children\'s playground, and a community garden, is expected to open by the end of next year. Residents have expressed overwhelming support for the project, calling it a much-needed green space in the heart of the city.\nQuestion: When is the park expected to be completed?', transcript: 'City Council approved 30M baht for new park in Sukhumvit. Features: jogging paths, playground, community garden. Opens end of next year.', question: 'When will it open?', questionTh: 'สวนสาธารณะจะเปิดเมื่อไร?\n\n💬 คำแปล: ข่าวท้องถิ่น: สภาเมืองอนุมัติงบประมาณ 30 ล้านบาทเพื่อสร้างสวนสาธารณะแห่งใหม่ในย่านสุขุมวิท สวนจะมีทางวิ่ง สนามเด็กเล่น และสวนชุมชน คาดว่าจะเปิดภายในสิ้นปีหน้า ชาวบ้านแสดงความสนับสนุนอย่างล้นหลาม เรียกว่าเป็นพื้นที่สีเขียวที่จำเป็นมากในใจกลางเมือง', choices: ['By the end of this year.', 'By the end of next year.', 'In five years.', 'No specific date was mentioned.'], answer: 1, explanationTh: '"expected to open by the end of next year" = คาดว่าจะเปิดภายในสิ้นปีหน้า', explanationEn: 'The report states the park "is expected to open by the end of next year".' },
                { audio: 'Talk: Today I\'d like to talk about the importance of sleep for academic performance. Research has consistently shown that students who get fewer than seven hours of sleep per night perform significantly worse on exams and have greater difficulty concentrating in class. In contrast, students who maintain a regular sleep schedule of seven to nine hours show improved memory retention and higher grades overall. So if you\'re thinking about pulling an all-nighter before your next exam, think again. A good night\'s rest might be the most effective study strategy of all.\nQuestion: What is the speaker\'s main argument?', transcript: 'Sleep affects academic performance. <7 hours = worse exams and concentration. 7-9 hours = better memory and grades. All-nighters are counterproductive.', question: 'What is the main argument?', questionTh: 'ข้อโต้แย้งหลักของผู้พูดคืออะไร?\n\n💬 คำแปล: วันนี้ผมอยากพูดเรื่องความสำคัญของการนอนหลับต่อผลการเรียน งานวิจัยแสดงให้เห็นอย่างสม่ำเสมอว่านักเรียนที่นอนน้อยกว่า 7 ชั่วโมงต่อคืนทำข้อสอบได้แย่กว่าอย่างมีนัยสำคัญ ในทางกลับกัน นักเรียนที่นอน 7-9 ชั่วโมงมีความจำดีกว่าและเกรดดีกว่าโดยรวม ดังนั้นถ้าคิดจะอ่านหนังสือทั้งคืนก่อนสอบ คิดใหม่นะ นอนหลับให้เพียงพออาจเป็นกลยุทธ์การเรียนที่ดีที่สุด', choices: ['Students should study all night before exams.', 'Adequate sleep is crucial for better academic performance.', 'Seven hours is too much sleep for students.', 'Memory and grades are unrelated to sleep.'], answer: 1, explanationTh: 'ผู้พูดโต้แย้งว่าการนอนหลับเพียงพอ (7-9 ชม.) สำคัญต่อผลการเรียน', explanationEn: 'The speaker argues that getting enough sleep is essential for academic success.' },
                { audio: 'Talk: We\'re now going to discuss the Great Barrier Reef, the world\'s largest coral reef system located off the coast of Australia. Stretching over 2,300 kilometers, it is home to an incredibly diverse range of marine life, including over 1,500 species of fish and 400 types of coral. However, rising ocean temperatures due to climate change have caused severe coral bleaching events in recent years, threatening the long-term survival of this natural wonder. Conservation efforts include reducing water pollution and establishing marine protected areas.\nQuestion: What is the main threat to the Great Barrier Reef?', transcript: 'Great Barrier Reef: 2,300 km, 1,500 fish species, 400 coral types. Threat: rising ocean temperatures causing coral bleaching. Conservation: reduce pollution + marine protected areas.', question: 'What is the main threat?', questionTh: 'อะไรเป็นภัยคุกคามหลักต่อ Great Barrier Reef?\n\n💬 คำแปล: ตอนนี้เราจะพูดเกี่ยวกับ Great Barrier Reef ระบบแนวปะการังที่ใหญ่ที่สุดในโลกนอกชายฝั่งออสเตรเลีย ยาวกว่า 2,300 กิโลเมตร เป็นที่อยู่ของสิ่งมีชีวิตทางทะเลที่หลากหลายอย่างเหลือเชื่อ รวมถึงปลากว่า 1,500 สายพันธุ์และปะการัง 400 ชนิด อย่างไรก็ตาม อุณหภูมิมหาสมุทรที่สูงขึ้นจากการเปลี่ยนแปลงสภาพภูมิอากาศทำให้เกิดปรากฏการณ์ปะการังฟอกขาวอย่างรุนแรง การอนุรักษ์รวมถึงการลดมลพิษทางน้ำและจัดตั้งเขตคุ้มครองทางทะเล', choices: ['Tourism.', 'Rising ocean temperatures causing coral bleaching.', 'Overfishing.', 'Oil spills.'], answer: 1, explanationTh: '"rising ocean temperatures... have caused severe coral bleaching" = อุณหภูมิทะเลสูงขึ้นทำให้ปะการังฟอกขาว', explanationEn: 'The text states that rising ocean temperatures cause coral bleaching events.' },
                { audio: 'Talk: And finally, our weather forecast for the coming week. Monday and Tuesday will see clear skies with temperatures reaching thirty-four degrees. However, from Wednesday onward, a tropical storm is expected to bring heavy rainfall and strong winds across the central and eastern regions. Flooding is possible in low-lying areas. Residents are advised to stock up on essentials and avoid unnecessary travel from Wednesday to Friday. We will keep you updated as the situation develops.\nQuestion: What should residents do from Wednesday to Friday?', transcript: 'Mon-Tue: clear, 34°C. Wed onward: tropical storm, heavy rain, strong winds. Flooding possible. Stock up on essentials, avoid travel Wed-Fri.', question: 'What should residents do?', questionTh: 'ชาวบ้านควรทำอะไรตั้งแต่วันพุธถึงศุกร์?\n\n💬 คำแปล: สุดท้าย พยากรณ์อากาศสัปดาห์หน้า จันทร์และอังคารท้องฟ้าแจ่มใส อุณหภูมิ 34 องศา อย่างไรก็ตามตั้งแต่วันพุธเป็นต้นไป พายุโซนร้อนจะนำฝนตกหนักและลมแรงมาทั่วภาคกลางและตะวันออก อาจเกิดน้ำท่วมในพื้นที่ลุ่มต่ำ แนะนำให้กักตุนสิ่งจำเป็นและหลีกเลี่ยงการเดินทางที่ไม่จำเป็นตั้งแต่พุธถึงศุกร์', choices: ['Go to the beach.', 'Prepare supplies and avoid unnecessary travel.', 'Evacuate immediately.', 'Continue daily activities as normal.'], answer: 1, explanationTh: '"stock up on essentials" = กักตุนสิ่งจำเป็น + "avoid unnecessary travel" = หลีกเลี่ยงการเดินทางที่ไม่จำเป็น', explanationEn: 'Residents should prepare by stocking up and avoiding travel.' }
            ]
        }
    ]
});
