LESSONS.push({
    id: 43,
    part: 1,
    isGame: true,
    titleTh: 'เก็งข้อสอบ Listening ชุดที่ 3',
    titleEn: 'Exam Prediction: Listening Set 3',
    icon: '🎯',
    sections: [
        {
            type: 'intro',
            title: '🎯 เก็งข้อสอบ Listening ชุดที่ 3',
            contentTh: 'ชุดที่ 3 เน้น Phrasal Verbs, สำนวนวัยรุ่น และ Monologues (การบรรยายเดี่ยว)',
            contentEn: 'Set 3 focuses on phrasal verbs, modern expressions, and monologues.',
            bullets: ['ข้อ 1-10: Short Dialogues (Phrasal Verbs + สำนวน)', 'ข้อ 11-15: Monologues / Talks', 'กดฟัง 🔊 ก่อนตอบทุกข้อ']
        },
        {
            type: 'quiz',
            title: '🎧 Listening Prediction Set 3 (15 ข้อ)',
            questions: [
                { audio: 'Woman: Have you figured out how to use the new software yet?\nMan: Not really. I\'ve been at it for hours and I\'m still going around in circles.\nQuestion: What does the man mean?', transcript: 'Woman: Have you figured out the new software?\nMan: I\'ve been at it for hours and I\'m still going around in circles.', question: 'What does the man mean?', questionTh: 'ผู้ชายหมายความว่าอย่างไร?\n\n💬 คำแปล: ผู้หญิง: หาวิธีใช้ซอฟต์แวร์ใหม่ได้ยัง? / ผู้ชาย: ไม่จริงๆ ฉันทำมาหลายชั่วโมงแล้วแต่ยังวนอยู่ที่เดิม', choices: ['He has mastered the software.', 'He is making no progress despite trying.', 'He enjoys using the software.', 'He is walking in circles.'], answer: 1, explanationTh: '"going around in circles" = วนอยู่ที่เดิม ไม่ได้คืบหน้าเลย', explanationEn: '"Going around in circles" means making no progress despite effort.' },
                { audio: 'Man: I think we need to cut back on our spending this month.\nWoman: Agreed. Let\'s start by eating out less.\nQuestion: What do they plan to do?', transcript: 'Man: We need to cut back on spending.\nWoman: Let\'s start by eating out less.', question: 'What do they plan to do?', questionTh: 'พวกเขาวางแผนจะทำอะไร?\n\n💬 คำแปล: ผู้ชาย: ฉันคิดว่าเราต้องลดค่าใช้จ่ายเดือนนี้ / ผู้หญิง: เห็นด้วย เริ่มจากกินข้างนอกให้น้อยลง', choices: ['Spend more money.', 'Reduce their expenses.', 'Move to a new house.', 'Get new jobs.'], answer: 1, explanationTh: '"cut back on" = ลด/ตัดทอน (ค่าใช้จ่าย)', explanationEn: '"Cut back on" means to reduce spending.' },
                { audio: 'Woman: Did the meeting with the investors pan out?\nMan: Unfortunately not. They pulled out at the last minute.\nQuestion: What happened with the investors?', transcript: 'Woman: Did the meeting pan out?\nMan: They pulled out at the last minute.', question: 'What happened?', questionTh: 'เกิดอะไรขึ้นกับนักลงทุน?\n\n💬 คำแปล: ผู้หญิง: การประชุมกับนักลงทุนเป็นไปด้วยดีไหม? / ผู้ชาย: น่าเสียดายไม่ พวกเขาถอนตัวในนาทีสุดท้าย', choices: ['They invested a large sum.', 'They withdrew from the deal at the last moment.', 'They asked for more time.', 'They arrived late to the meeting.'], answer: 1, explanationTh: '"pan out" = ออกมาดี/สำเร็จ + "pulled out" = ถอนตัว + "at the last minute" = ในนาทีสุดท้าย', explanationEn: '"Pulled out" means withdrew. "At the last minute" means at the very end.' },
                { audio: 'Man: I\'m fed up with this commute. It takes me two hours each way.\nWoman: Have you considered working from home a few days a week?\nQuestion: How does the man feel?', transcript: 'Man: I\'m fed up with this commute. Two hours each way.\nWoman: Have you considered working from home?', question: 'How does the man feel?', questionTh: 'ผู้ชายรู้สึกอย่างไร?\n\n💬 คำแปล: ผู้ชาย: ฉันเบื่อหน่ายการเดินทางไปทำงานมาก ใช้เวลา 2 ชั่วโมงต่อเที่ยว / ผู้หญิง: เคยคิดจะทำงานจากบ้านสักสองสามวันต่อสัปดาห์ไหม?', choices: ['He enjoys the long commute.', 'He is frustrated and tired of commuting.', 'He wants to move closer to work.', 'He recently got a new car.'], answer: 1, explanationTh: '"fed up with" = เบื่อหน่าย/เอือมระอากับสิ่งนั้น', explanationEn: '"Fed up with" means extremely tired and annoyed by something.' },
                { audio: 'Woman: The boss just turned down my proposal without even reading it.\nMan: That must be frustrating. Maybe try pitching it again when he\'s less busy.\nQuestion: What happened to the woman\'s proposal?', transcript: 'Woman: The boss turned down my proposal without reading it.\nMan: Try pitching it again when he\'s less busy.', question: 'What happened?', questionTh: 'เกิดอะไรขึ้นกับข้อเสนอของผู้หญิง?\n\n💬 คำแปล: ผู้หญิง: เจ้านายเพิ่งปฏิเสธข้อเสนอของฉันโดยไม่อ่านด้วยซ้ำ / ผู้ชาย: น่าหงุดหงิดมาก ลองเสนออีกทีตอนเขาไม่ยุ่งนัก', choices: ['It was approved immediately.', 'It was rejected without being reviewed.', 'It was sent to another department.', 'It was postponed.'], answer: 1, explanationTh: '"turned down" = ปฏิเสธ + "without even reading it" = โดยไม่อ่านด้วยซ้ำ', explanationEn: '"Turned down" means rejected.' },
                { audio: 'Man: I ran into your brother at the gym yesterday.\nWoman: Oh really? I didn\'t know he\'d taken up exercising.\nQuestion: What does "ran into" mean?', transcript: 'Man: I ran into your brother at the gym.\nWoman: I didn\'t know he\'d taken up exercising.', question: 'What does "ran into" mean here?', questionTh: '"ran into" ในที่นี้แปลว่าอะไร?\n\n💬 คำแปล: ผู้ชาย: ฉันบังเอิญเจอพี่ชายของคุณที่ยิมเมื่อวาน / ผู้หญิง: อ้อจริงเหรอ? ฉันไม่รู้ว่าเขาเริ่มออกกำลังกายแล้ว', choices: ['Collided with physically.', 'Met by chance.', 'Chased after.', 'Argued with.'], answer: 1, explanationTh: '"ran into" = บังเอิญเจอ/พบโดยไม่ได้นัดหมาย + "taken up" = เริ่มทำ (กิจกรรมใหม่)', explanationEn: '"Ran into" means met unexpectedly. "Taken up" means started a new activity.' },
                { audio: 'Woman: Could you look after my cat while I\'m on vacation next week?\nMan: I\'d be happy to, but I\'m allergic. Maybe ask Lisa?\nQuestion: Why can\'t the man help?', transcript: 'Woman: Could you look after my cat next week?\nMan: I\'d be happy to, but I\'m allergic.', question: 'Why can\'t the man help?', questionTh: 'ทำไมผู้ชายช่วยไม่ได้?\n\n💬 คำแปล: ผู้หญิง: ช่วยดูแลแมวของฉันตอนฉันไปพักร้อนสัปดาห์หน้าได้ไหม? / ผู้ชาย: ยินดีเลย แต่ฉันแพ้ ลองถาม Lisa ดูไหม?', choices: ['He is also going on vacation.', 'He is allergic to cats.', 'He does not like cats.', 'He is too busy with work.'], answer: 1, explanationTh: '"look after" = ดูแล + "I\'m allergic" = ฉันแพ้ (แพ้แมว)', explanationEn: '"Look after" means take care of. He is allergic to cats.' },
                { audio: 'Man: The client wants us to come up with a completely new marketing strategy by Friday.\nWoman: That\'s a tall order, but I think we can pull it off if we work together.\nQuestion: What does the woman think about the task?', transcript: 'Man: The client wants a new strategy by Friday.\nWoman: That\'s a tall order, but we can pull it off.', question: 'What does the woman think?', questionTh: 'ผู้หญิงคิดอย่างไรเกี่ยวกับงานนี้?\n\n💬 คำแปล: ผู้ชาย: ลูกค้าต้องการให้เราคิดกลยุทธ์การตลาดใหม่ทั้งหมดภายในวันศุกร์ / ผู้หญิง: นั่นเป็นงานที่ยากมาก แต่ฉันคิดว่าเราทำสำเร็จได้ถ้าทำงานร่วมกัน', choices: ['It is impossible to complete.', 'It is challenging but achievable with teamwork.', 'It is very easy.', 'They should refuse the client.'], answer: 1, explanationTh: '"tall order" = งานที่ยากมาก/ท้าทาย + "pull it off" = ทำสำเร็จได้', explanationEn: '"A tall order" means a difficult task. "Pull it off" means to succeed despite difficulty.' },
                { audio: 'Woman: I think we should put off the trip until the weather improves.\nMan: Good call. There\'s no point in going if it\'s going to rain all week.\nQuestion: What do they decide?', transcript: 'Woman: Let\'s put off the trip until weather improves.\nMan: Good call. No point going if it rains all week.', question: 'What do they decide?', questionTh: 'พวกเขาตัดสินใจอย่างไร?\n\n💬 คำแปล: ผู้หญิง: ฉันคิดว่าเราควรเลื่อนทริปออกไปจนกว่าอากาศจะดีขึ้น / ผู้ชาย: ความคิดดี ไม่มีประโยชน์ที่จะไปถ้าฝนจะตกทั้งสัปดาห์', choices: ['Cancel the trip permanently.', 'Postpone the trip until better weather.', 'Go on the trip regardless of weather.', 'Take a different trip.'], answer: 1, explanationTh: '"put off" = เลื่อนออกไป + "Good call" = ความคิดดี', explanationEn: '"Put off" means postpone. "Good call" means a wise decision.' },
                { audio: 'Man: I finally got around to cleaning out the garage this weekend.\nWoman: About time! It\'s been a mess for months.\nQuestion: What does the woman imply?', transcript: 'Man: I finally got around to cleaning the garage.\nWoman: About time! It\'s been a mess for months.', question: 'What does the woman imply?', questionTh: 'ผู้หญิงสื่ออะไร?\n\n💬 คำแปล: ผู้ชาย: ในที่สุดฉันก็ได้ทำความสะอาดโรงรถสุดสัปดาห์นี้ / ผู้หญิง: ถึงเวลาแล้ว! มันรกมาหลายเดือนแล้ว', choices: ['She is surprised he cleaned it.', 'She thinks he should have done it much sooner.', 'She does not care about the garage.', 'She wants to help him clean.'], answer: 1, explanationTh: '"got around to" = ในที่สุดก็ได้ทำ (สิ่งที่ผัดวันประกันพรุ่ง) + "About time!" = ถึงเวลาแล้ว! (ควรทำนานแล้ว)', explanationEn: '"Got around to" means finally doing something delayed. "About time" implies it should have been done earlier.' },
                { audio: 'Talk: Good morning everyone. Before we begin today\'s lecture on behavioral economics, I\'d like to remind you that next week\'s midterm exam will cover chapters one through six of the textbook, as well as all lecture materials presented in class. The exam will consist of forty multiple-choice questions and two short-answer essays. Please note that calculators will not be permitted.\nQuestion: What is the speaker mainly doing?', transcript: 'Midterm exam: chapters 1-6 plus all lecture materials. 40 multiple-choice + 2 short-answer essays. No calculators.', question: 'What is the speaker doing?', questionTh: 'ผู้พูดกำลังทำอะไร?\n\n💬 คำแปล: สวัสดีครับทุกคน ก่อนเริ่มบรรยายเรื่องเศรษฐศาสตร์พฤติกรรมวันนี้ ผมอยากเตือนว่าสอบกลางภาคสัปดาห์หน้าจะครอบคลุมบทที่ 1-6 ของตำราเรียนรวมถึงเนื้อหาบรรยายทั้งหมด ข้อสอบประกอบด้วยปรนัย 40 ข้อและเรียงความตอบสั้น 2 ข้อ เครื่องคิดเลขไม่อนุญาตให้ใช้', choices: ['Giving the midterm exam.', 'Providing information about an upcoming exam.', 'Cancelling the midterm.', 'Assigning a new textbook.'], answer: 1, explanationTh: 'อาจารย์กำลังแจ้งรายละเอียดเกี่ยวกับสอบกลางภาคที่จะมาถึง', explanationEn: 'The professor is informing students about the midterm exam details.' },
                { audio: 'Talk: Thank you for calling Riverside Medical Clinic. Our office hours are Monday through Friday, 8 AM to 6 PM, and Saturday from 9 AM to 1 PM. We are closed on Sundays and public holidays. If you are experiencing a medical emergency, please hang up and dial 1669 immediately. To schedule an appointment, press 1. To speak with a nurse, press 2. For billing inquiries, press 3.\nQuestion: When is the clinic closed?', transcript: 'Office hours: Mon-Fri 8AM-6PM, Sat 9AM-1PM. Closed Sundays and public holidays. Emergency: dial 1669.', question: 'When is the clinic closed?', questionTh: 'คลินิกปิดเมื่อไร?\n\n💬 คำแปล: ขอบคุณที่โทรหาคลินิกริเวอร์ไซด์ เวลาทำการ จันทร์-ศุกร์ 8:00-18:00 เสาร์ 9:00-13:00 ปิดวันอาทิตย์และวันหยุดนักขัตฤกษ์ หากมีเหตุฉุกเฉิน กรุณาวางสายและโทร 1669 ทันที กด 1 นัดหมาย กด 2 พูดคุยกับพยาบาล กด 3 สอบถามค่าใช้จ่าย', choices: ['Monday and Friday.', 'Saturday afternoon and Sunday.', 'Sundays and public holidays.', 'Every day after 6 PM.'], answer: 2, explanationTh: '"closed on Sundays and public holidays" = ปิดวันอาทิตย์และวันหยุดนักขัตฤกษ์', explanationEn: 'The recording clearly states "closed on Sundays and public holidays".' },
                { audio: 'Talk: Good afternoon, passengers. This is your captain speaking. We are currently cruising at an altitude of thirty-five thousand feet and expect to arrive at Suvarnabhumi Airport in approximately one hour and forty minutes. The weather in Bangkok is partly cloudy with a temperature of thirty-two degrees Celsius. We may experience some light turbulence as we begin our descent, so I\'d like to ask that you remain seated with your seatbelts fastened. Thank you.\nQuestion: What does the captain ask passengers to do?', transcript: 'Cruising at 35,000 feet. Arriving Suvarnabhumi in 1 hour 40 minutes. Bangkok: partly cloudy, 32°C. Light turbulence expected during descent. Remain seated with seatbelts.', question: 'What does the captain ask?', questionTh: 'กัปตันขอให้ผู้โดยสารทำอะไร?\n\n💬 คำแปล: สวัสดีตอนบ่ายครับผู้โดยสาร นี่คือกัปตันของคุณ ขณะนี้เราบินอยู่ที่ความสูง 35,000 ฟุต คาดว่าจะถึงสนามบินสุวรรณภูมิในอีกประมาณ 1 ชั่วโมง 40 นาที อากาศในกรุงเทพมีเมฆบางส่วน อุณหภูมิ 32 องศา อาจมีความปั่นป่วนเล็กน้อยระหว่างลดระดับ ขอให้นั่งอยู่กับที่และรัดเข็มขัดนิรภัยด้วยครับ', choices: ['Prepare for landing immediately.', 'Stay seated and keep seatbelts on.', 'Open the window shades.', 'Turn off electronic devices.'], answer: 1, explanationTh: '"remain seated with your seatbelts fastened" = นั่งอยู่กับที่และรัดเข็มขัด', explanationEn: 'The captain specifically asks passengers to remain seated with seatbelts fastened.' },
                { audio: 'Talk: Attention all staff. Starting next Monday, the company will implement a new recycling program. Three separate bins will be placed in the break room and near the elevators: blue for paper, green for glass and plastic, and black for general waste. Please make an effort to sort your trash accordingly. Any questions can be directed to the facilities management team on extension 4502.\nQuestion: How many types of bins will be provided?', transcript: 'New recycling program next Monday. Blue = paper, Green = glass/plastic, Black = general waste. Questions: extension 4502.', question: 'How many types of bins?', questionTh: 'จะมีถังขยะกี่ประเภท?\n\n💬 คำแปล: แจ้งพนักงานทุกท่าน เริ่มวันจันทร์หน้าบริษัทจะเริ่มโปรแกรมรีไซเคิลใหม่ จะมีถังแยก 3 ถังในห้องพักและใกล้ลิฟต์: น้ำเงินสำหรับกระดาษ เขียวสำหรับแก้วและพลาสติก ดำสำหรับขยะทั่วไป กรุณาแยกขยะตามที่กำหนด สอบถามเพิ่มเติมที่ทีมจัดการอาคาร สายภายใน 4502', choices: ['Two.', 'Three.', 'Four.', 'Five.'], answer: 1, explanationTh: 'มี 3 ถัง: น้ำเงิน (กระดาษ), เขียว (แก้ว/พลาสติก), ดำ (ขยะทั่วไป)', explanationEn: 'Three bins: blue (paper), green (glass/plastic), black (general waste).' },
                { audio: 'Talk: Good evening and welcome to the City Arts Center. Tonight\'s performance of Romeo and Juliet will begin at seven thirty. Please silence your mobile phones before entering the auditorium. Late arrivals will be seated during the first intermission only. Photography and video recording are strictly prohibited throughout the performance. The show runs approximately two hours with a fifteen-minute intermission. Enjoy the show.\nQuestion: When will latecomers be allowed to enter?', transcript: 'Romeo and Juliet starts at 7:30. Silence phones. Late arrivals seated at first intermission only. No photography/video. Show: ~2 hours with 15-min intermission.', question: 'When will latecomers be seated?', questionTh: 'คนที่มาสายจะได้เข้าเมื่อไร?\n\n💬 คำแปล: สวัสดีตอนเย็นและยินดีต้อนรับสู่ City Arts Center การแสดง Romeo and Juliet คืนนี้จะเริ่มเวลา 19:30 กรุณาปิดเสียงโทรศัพท์ก่อนเข้าหอประชุม ผู้ที่มาสายจะได้รับอนุญาตให้เข้านั่งในช่วงพักครึ่งแรกเท่านั้น ห้ามถ่ายรูปและวิดีโอตลอดการแสดง การแสดงยาวประมาณ 2 ชั่วโมง พักครึ่ง 15 นาที', choices: ['They cannot enter at all.', 'During the first intermission only.', 'At any time during the show.', 'Before the show starts.'], answer: 1, explanationTh: '"Late arrivals will be seated during the first intermission only" = เข้าได้เฉพาะช่วงพักครึ่งแรกเท่านั้น', explanationEn: 'Latecomers can only enter during the first intermission.' }
            ]
        }
    ]
});
