LESSONS.push({
    id: 45,
    part: 1,
    isGame: true,
    titleTh: 'เก็งข้อสอบ Listening ชุดที่ 5 (Final)',
    titleEn: 'Exam Prediction: Listening Set 5 (Final)',
    icon: '🏅',
    sections: [
        {
            type: 'intro',
            title: '🏅 เก็งข้อสอบ Listening ชุดที่ 5 (ชุดสุดท้าย)',
            contentTh: 'ชุดสุดท้าย! รวมความยากทุกระดับ สำนวนขั้นสูง Phrasal Verbs ซ้อน และ Academic Talks ถ้าผ่านชุดนี้ได้ 12/15 ขึ้นไป แปลว่าพร้อมสอบ Listening จริงแล้ว!',
            contentEn: 'The final set! Mixed difficulty with advanced idioms and academic talks. Score 12/15+ means you are exam-ready!',
            bullets: ['รวมมิตรทุกสไตล์: สำนวน + สถานการณ์ + Talks', 'ตั้งเป้า 12/15 ขึ้นไป = พร้อมสอบ!', 'กดฟัง 🔊 ก่อนตอบทุกข้อ']
        },
        {
            type: 'quiz',
            title: '🎧 Listening Final Set (15 ข้อ)',
            questions: [
                { audio: 'Woman: I\'ve been on the fence about applying for that master\'s program.\nMan: What\'s holding you back? You have the grades and the experience.\nQuestion: What does the woman mean?', transcript: 'Woman: I\'ve been on the fence about the master\'s program.\nMan: What\'s holding you back?', question: 'What does the woman mean?', questionTh: 'ผู้หญิงหมายความว่าอย่างไร?\n\n💬 คำแปล: ผู้หญิง: ฉันยังลังเลเรื่องสมัครป.โท / ผู้ชาย: อะไรที่ทำให้คุณลังเล? คุณมีทั้งเกรดและประสบการณ์', choices: ['She has decided to apply.', 'She is undecided about applying.', 'She was rejected from the program.', 'She is sitting on a fence.'], answer: 1, explanationTh: '"on the fence" = ลังเลใจ ตัดสินใจไม่ได้ + "holding you back" = อะไรที่ยับยั้งคุณ', explanationEn: '"On the fence" means undecided. "Holding you back" means preventing you.' },
                { audio: 'Man: The new marketing campaign was a shot in the dark, but it paid off big time.\nWoman: Sometimes taking risks is the only way to succeed.\nQuestion: What happened with the campaign?', transcript: 'Man: The campaign was a shot in the dark but paid off big time.\nWoman: Taking risks is sometimes needed.', question: 'What happened?', questionTh: 'เกิดอะไรขึ้นกับแคมเปญ?\n\n💬 คำแปล: ผู้ชาย: แคมเปญการตลาดใหม่เป็นการเสี่ยงในที่มืด แต่มันให้ผลตอบแทนมหาศาล / ผู้หญิง: บางทีการเสี่ยงเป็นทางเดียวที่จะสำเร็จ', choices: ['It failed completely.', 'It was a risky attempt that succeeded greatly.', 'It was carefully planned.', 'It was cancelled.'], answer: 1, explanationTh: '"shot in the dark" = การเสี่ยง/ลองมั่ว + "paid off big time" = ให้ผลตอบแทนมหาศาล', explanationEn: '"A shot in the dark" = a guess/risk. "Paid off big time" = succeeded enormously.' },
                { audio: 'Woman: Have you heard? They\'re laying off thirty percent of the workforce.\nMan: I had a feeling it was coming. Sales have been declining for months.\nQuestion: What is happening at the company?', transcript: 'Woman: They\'re laying off 30% of the workforce.\nMan: Sales have been declining for months.', question: 'What is happening?', questionTh: 'เกิดอะไรขึ้นที่บริษัท?\n\n💬 คำแปล: ผู้หญิง: ได้ยินไหม? พวกเขาจะเลิกจ้างพนักงาน 30% / ผู้ชาย: ฉันรู้สึกว่ามันจะมา ยอดขายลดลงมาหลายเดือนแล้ว', choices: ['The company is hiring.', 'The company is reducing its workforce significantly.', 'Sales have been increasing.', 'Workers are getting promoted.'], answer: 1, explanationTh: '"laying off" = เลิกจ้าง/ปลดออก + 30% = จำนวนมาก', explanationEn: '"Laying off" means dismissing employees. 30% is a significant reduction.' },
                { audio: 'Man: I think Lisa\'s been spreading rumors about me behind my back.\nWoman: Don\'t jump to conclusions. Maybe you should talk to her directly.\nQuestion: What does the woman advise?', transcript: 'Man: Lisa is spreading rumors behind my back.\nWoman: Don\'t jump to conclusions. Talk to her.', question: 'What does the woman advise?', questionTh: 'ผู้หญิงแนะนำอะไร?\n\n💬 คำแปล: ผู้ชาย: ฉันคิดว่า Lisa ปล่อยข่าวลือเรื่องฉันลับหลัง / ผู้หญิง: อย่าด่วนสรุป ลองไปคุยกับเธอตรงๆ ดีกว่า', choices: ['Ignore the rumors.', 'Don\'t make assumptions and talk to Lisa first.', 'Spread rumors about Lisa too.', 'Report Lisa to HR.'], answer: 1, explanationTh: '"jump to conclusions" = ด่วนสรุป + "behind my back" = ลับหลัง → แนะนำให้คุยตรงๆ', explanationEn: '"Don\'t jump to conclusions" means don\'t assume. She advises talking directly.' },
                { audio: 'Woman: How\'s the renovation going?\nMan: It\'s been a money pit. Every time we fix one thing, another problem pops up.\nQuestion: What does the man mean?', transcript: 'Woman: How\'s the renovation?\nMan: It\'s been a money pit. Fix one thing, another pops up.', question: 'What does the man mean?', questionTh: 'ผู้ชายหมายความว่าอย่างไร?\n\n💬 คำแปล: ผู้หญิง: การปรับปรุงบ้านเป็นไงบ้าง? / ผู้ชาย: มันเป็นหลุมเงินเลย แก้อะไรเสร็จก็มีปัญหาใหม่โผล่มา', choices: ['The renovation is going smoothly.', 'The renovation keeps costing more and more money.', 'He found money during renovation.', 'The renovation is almost complete.'], answer: 1, explanationTh: '"money pit" = หลุมเงิน (สิ่งที่กินเงินไปเรื่อยๆ ไม่หยุด)', explanationEn: '"A money pit" is something that continually requires spending more and more money.' },
                { audio: 'Man: I\'ve been meaning to get in touch with you, but work has been crazy.\nWoman: Tell me about it. I haven\'t had a day off in three weeks.\nQuestion: How does the woman feel?', transcript: 'Man: I\'ve been meaning to get in touch but work is crazy.\nWoman: Tell me about it. No day off in 3 weeks.', question: 'How does the woman feel?', questionTh: 'ผู้หญิงรู้สึกอย่างไร?\n\n💬 คำแปล: ผู้ชาย: ฉันตั้งใจจะติดต่อคุณ แต่งานบ้ามาก / ผู้หญิง: เข้าใจดี! ฉันไม่ได้หยุดเลย 3 สัปดาห์แล้ว', choices: ['She has plenty of free time.', 'She completely relates because she is also very busy.', 'She is angry at the man.', 'She wants to tell him a story.'], answer: 1, explanationTh: '"Tell me about it" = เข้าใจดี! ฉันก็เหมือนกัน (เห็นด้วยอย่างยิ่ง ไม่ใช่ขอให้เล่า)', explanationEn: '"Tell me about it" is an expression of agreement, meaning "I know exactly how you feel".' },
                { audio: 'Woman: The exam results came out today. How did you do?\nMan: Let\'s just say I won\'t be celebrating tonight.\nQuestion: How did the man perform on the exam?', transcript: 'Woman: How did you do on the exam?\nMan: Let\'s just say I won\'t be celebrating.', question: 'How did he do?', questionTh: 'ผู้ชายทำข้อสอบได้เป็นอย่างไร?\n\n💬 คำแปล: ผู้หญิง: ผลสอบออกวันนี้ ทำได้ไงบ้าง? / ผู้ชาย: พูดแค่ว่า ฉันจะไม่ฉลองคืนนี้', choices: ['He performed excellently.', 'He did poorly on the exam.', 'He has not checked his results yet.', 'He passed with flying colors.'], answer: 1, explanationTh: '"won\'t be celebrating" = จะไม่ฉลอง → หมายความว่าผลสอบไม่ดี', explanationEn: 'Not celebrating implies he did not do well on the exam.' },
                { audio: 'Man: Should we go with the cheaper option or invest in the premium package?\nWoman: You get what you pay for. I say go with the premium.\nQuestion: What does the woman recommend?', transcript: 'Man: Cheaper option or premium package?\nWoman: You get what you pay for. Go premium.', question: 'What does she recommend?', questionTh: 'ผู้หญิงแนะนำอะไร?\n\n💬 คำแปล: ผู้ชาย: เราควรเลือกตัวเลือกที่ถูกกว่าหรือลงทุนในแพ็กเกจพรีเมียม? / ผู้หญิง: ของถูกก็ได้ของถูก ฉันว่าเลือกพรีเมียมเลย', choices: ['The cheaper option to save money.', 'The premium package because quality matches price.', 'Neither option.', 'A completely different product.'], answer: 1, explanationTh: '"You get what you pay for" = ของถูกก็ได้ของถูก (จ่ายมากได้ของดี) → แนะนำแพ็กเกจพรีเมียม', explanationEn: '"You get what you pay for" means quality corresponds to price. She recommends premium.' },
                { audio: 'Woman: I hear the company is going through a rough patch financially.\nMan: That\'s putting it mildly. We might not survive the quarter.\nQuestion: How serious is the financial situation?', transcript: 'Woman: The company is going through a rough patch.\nMan: That\'s putting it mildly. We might not survive the quarter.', question: 'How serious is it?', questionTh: 'สถานการณ์ทางการเงินร้ายแรงแค่ไหน?\n\n💬 คำแปล: ผู้หญิง: ฉันได้ยินว่าบริษัทกำลังผ่านช่วงลำบากทางการเงิน / ผู้ชาย: พูดน้อยไปด้วยซ้ำ เราอาจจะอยู่ไม่รอดไตรมาสนี้', choices: ['It is a minor issue.', 'It is extremely critical and potentially fatal for the company.', 'The company is doing fine.', 'It is improving rapidly.'], answer: 1, explanationTh: '"rough patch" = ช่วงลำบาก + "putting it mildly" = พูดน้อยไป (มันแย่กว่านั้นอีก) + "might not survive" = อาจอยู่ไม่รอด', explanationEn: '"Rough patch" = difficult period. "Putting it mildly" = an understatement. The situation is dire.' },
                { audio: 'Man: My boss gave me the green light to work remotely two days a week.\nWoman: That\'s fantastic! I wish my company offered that flexibility.\nQuestion: What did the man\'s boss do?', transcript: 'Man: Boss gave me the green light to work remotely.\nWoman: That\'s fantastic!', question: 'What did the boss do?', questionTh: 'เจ้านายทำอะไร?\n\n💬 คำแปล: ผู้ชาย: เจ้านายฉันให้ไฟเขียว (อนุมัติ) ให้ทำงานจากที่บ้าน 2 วันต่อสัปดาห์ / ผู้หญิง: ดีจัง! อยากให้บริษัทฉันมีความยืดหยุ่นแบบนั้นบ้าง', choices: ['Rejected his request.', 'Approved his request to work from home.', 'Promoted him.', 'Gave him a green traffic light.'], answer: 1, explanationTh: '"gave me the green light" = อนุมัติ/ให้ไฟเขียว', explanationEn: '"Gave the green light" means approved or gave permission.' },
                { audio: 'Talk: Today we will explore one of the most significant inventions of the 20th century: the internet. Originally developed as a military communication network called ARPANET in the late 1960s, the internet has evolved into a global system connecting billions of devices worldwide. The introduction of the World Wide Web by Tim Berners-Lee in 1991 made the internet accessible to the general public for the first time. Today, the internet supports everything from online commerce and social media to telemedicine and remote education, fundamentally transforming how we live, work, and communicate.\nQuestion: What was the original purpose of the internet?', transcript: 'Internet started as ARPANET (military network) in late 1960s. WWW by Tim Berners-Lee in 1991 made it public. Now supports commerce, social media, telemedicine, education.', question: 'Original purpose?', questionTh: 'จุดประสงค์เดิมของอินเทอร์เน็ตคืออะไร?\n\n💬 คำแปล: วันนี้เราจะสำรวจหนึ่งในสิ่งประดิษฐ์สำคัญที่สุดของศตวรรษที่ 20: อินเทอร์เน็ต เดิมพัฒนาขึ้นเป็นเครือข่ายสื่อสารทางทหารชื่อ ARPANET ในปลายทศวรรษ 1960 อินเทอร์เน็ตพัฒนาเป็นระบบโลกที่เชื่อมอุปกรณ์หลายพันล้านเครื่อง การเปิดตัว World Wide Web โดย Tim Berners-Lee ในปี 1991 ทำให้ประชาชนทั่วไปเข้าถึงได้เป็นครั้งแรก', choices: ['Social media.', 'Military communication.', 'Online shopping.', 'Education.'], answer: 1, explanationTh: '"military communication network called ARPANET" = เครือข่ายสื่อสารทางทหาร', explanationEn: 'It was originally a military communication network (ARPANET).' },
                { audio: 'Talk: A recent study published in the Journal of Nutrition found that consuming a Mediterranean diet, rich in olive oil, fish, whole grains, fruits, and vegetables, can reduce the risk of heart disease by up to thirty percent. The study followed ten thousand participants over a period of twelve years and also found links between the diet and lower rates of type 2 diabetes and certain cancers. Researchers recommend gradually incorporating Mediterranean dietary principles rather than making drastic changes overnight.\nQuestion: What does the study recommend?', transcript: 'Mediterranean diet: olive oil, fish, whole grains, fruits, veggies. Reduces heart disease risk by 30%. Study: 10,000 participants over 12 years. Also reduces diabetes and cancer. Gradual changes recommended.', question: 'What is recommended?', questionTh: 'การศึกษาแนะนำอะไร?\n\n💬 คำแปล: การศึกษาล่าสุดในวารสารโภชนาการพบว่าอาหารเมดิเตอร์เรเนียนที่อุดมด้วยน้ำมันมะกอก ปลา ธัญพืช ผลไม้ และผัก สามารถลดความเสี่ยงโรคหัวใจได้ถึง 30% การศึกษาติดตามผู้เข้าร่วม 10,000 คนเป็นเวลา 12 ปี นักวิจัยแนะนำให้ค่อยๆ ปรับเปลี่ยนอาหารแบบค่อยเป็นค่อยไป ไม่ใช่เปลี่ยนแบบฮวบฮาบ', choices: ['Make drastic dietary changes immediately.', 'Gradually adopt Mediterranean eating habits.', 'Avoid all fats and oils.', 'Only eat fish and vegetables.'], answer: 1, explanationTh: '"gradually incorporating" = ค่อยๆ ปรับเปลี่ยน + "rather than making drastic changes" = ไม่ใช่เปลี่ยนทันที', explanationEn: 'The study recommends gradual incorporation rather than drastic overnight changes.' },
                { audio: 'Talk: In conclusion, the evidence strongly suggests that regular physical exercise offers benefits that extend far beyond physical fitness. Studies have shown that even moderate exercise, such as thirty minutes of brisk walking five days a week, can significantly reduce symptoms of depression and anxiety. Exercise triggers the release of endorphins, often called feel-good hormones, which improve mood and reduce stress. Moreover, regular physical activity has been linked to improved cognitive function and better sleep quality. So the next time you feel overwhelmed, consider going for a walk or a swim. Your mind will thank you.\nQuestion: According to the speaker, what benefit of exercise is the main focus?', transcript: 'Exercise benefits beyond fitness: reduces depression/anxiety, releases endorphins, improves mood and cognition, better sleep. 30 min brisk walk 5 days/week is enough.', question: 'What is the main focus?', questionTh: 'ประโยชน์ของการออกกำลังกายที่ผู้พูดเน้นคืออะไร?\n\n💬 คำแปล: โดยสรุป หลักฐานชี้ชัดว่าการออกกำลังกายสม่ำเสมอมีประโยชน์ไกลเกินกว่าร่างกาย แม้แค่ออกกำลังกายปานกลาง เช่น เดินเร็ว 30 นาที 5 วันต่อสัปดาห์ ก็ลดอาการซึมเศร้าและวิตกกังวลได้มาก การออกกำลังกายกระตุ้นการหลั่งเอนดอร์ฟิน (ฮอร์โมนแห่งความสุข) ที่ทำให้อารมณ์ดีขึ้นและลดความเครียด', choices: ['Weight loss.', 'The mental and psychological health benefits.', 'Building muscle.', 'Training for sports competitions.'], answer: 1, explanationTh: 'ผู้พูดเน้นประโยชน์ด้านสุขภาพจิต: ลดซึมเศร้า ลดวิตกกังวล อารมณ์ดีขึ้น', explanationEn: 'The focus is on mental health benefits: reducing depression, anxiety, improving mood and cognition.' }
            ]
        }
    ]
});
